downstreamadapter/writer/config.go, downstreamadapter/writer/helper.go, downstreamadapter/writer/mysql_writer.go
When dry-run is enabled, all SQL will not be executed downstream. This is useful for testing when there are not enough resources for downstream.
By adding dry-run=true in sink-uri.
"sink_uri":"mysql://root@127.0.0.1:3306?dry-run=true"
=> sink: add dry run mode for mysql sink

downstreamadapter/writer/mysql_writer.go, downstreamadapter/writer/sql_builder.go, downstreamadapter/writer/sql_builder_benchmark_test.go, downstreamadapter/writer/sql_builder_test.go, pkg/common/table_info.go
This PR significantly enhances the performance of our SQL query building functions, specifically targeting `buildInsert` and `buildUpdate`.
- `buildInsert`: 2.5x performance boost
- `buildUpdate`: 1.5x performance boost
I've optimized the internal logic of these functions to reduce computational overhead and memory allocation. These enhancements will lead to faster query generation, particularly beneficial for operations involving large tables (has many columns).
- Faster query generation for INSERT and UPDATE operations
- Reduced latency in database-heavy operations
- Improved overall application performance, especially in data-intensive scenarios
Performance benchmarks have been run to verify the improvements.
=> writer: optimize sql builder

logservice/eventstore/eventstore.go
New the db batch lazily, to reduce memory allocation when there is no running workload
=> event store reduce memory allocation

pkg/eventservice/event_broker.go
With Select, SendWatermark will occupy 14% cpu. Without it, it only occupy 4%
=> Fix the cpu cost of too many select statement

cmd/main.go
This PR introduces a `NEWARCH` environment variable to control command execution in TiCDC. When `NEWARCH=true` is set, the new architecture commands are activated automatically, removing the need to specify the `--newarch` flag in each command line call. This enhancement simplifies command usage by offering a more seamless way to opt into the new architecture.
To activate the new architecture commands:
```bash
export NEWARCH=true
./cdc_binary <command>
```
When `NEWARCH` is not set or set to false, TiFlow’s original command set will remain the default behavior.
This update simplifies user workflows and enables easier testing and deployment of the new architecture commands.
=> newarch: add `NEWARCH` env variable to running newarch commands

cmd/main.go
This PR introduces a `TICDC_NEWARCH` environment variable to control command execution in TiCDC. When `TICDC_NEWARCH=true` is set, the new architecture commands are activated automatically, removing the need to specify the `--newarch` flag in each command line call. This enhancement simplifies command usage by offering a more seamless way to opt into the new architecture.
To activate the new architecture commands:
```bash
export TICDC_NEWARCH=true
./cdc_binary <command>
```
When `TICDC_NEWARCH` is not set or set to false, TiFlow’s original command set will remain the default behavior.
This update simplifies user workflows and enables easier testing and deployment of the new architecture commands.
=> newarch: rename `NEWARCH` env variable to `TICDC_NEWARCH`

downstreamadapter/eventcollector/event_collector.go, downstreamadapter/eventcollector/helper.go, metrics/grafana/ticdc_new_arch_v2.json
=> eventcollector: add more metrics to help debug the lag

pkg/eventservice/dispatcher_stat.go, pkg/eventservice/event_broker.go
=> log: remove uselsee log

.github/workflows/integration_test_mysql.yaml, pkg/sink/mysql/mysql_writer.go
=> test: fix safe mode test 

Makefile
Issue Number: close #826
This PR updates the cdc version command to always display the Git Commit Hash and Branch from the new architecture repository. Since TiCDC binaries are built exclusively from the new architecture, this change ensures consistency in version reporting.
Users can still find the legacy architecture’s Git Commit Hash and build details in the go.mod file, e.g.:
```
github.com/pingcap/tiflow v0.0.0-20241023094956-dd2d54ad4c19  
```
- No code
No.
No.
```release-note
None
```
=> version: unify Git Commit Hash and Branch info for legacy and new architectures

Makefile
Issue Number: close #841
**Pull Request Description**
This PR simplifies the logic for retrieving the `RELEASE_VERSION` variable in the Makefile.
**Changes**:
* Replaces the complex branch and tag regex checks with a direct call to `git describe --tags --dirty`.
* Improves compatibility across different platforms and Bash versions.
* Ensures consistent behavior in environments with different shell implementations.
- Manual test
```release-note
None
```
=> makefile: simplify makefile version retrieval for compatibility

Makefile
**Pull Request Description**
This PR updates the Makefile logic for setting the `RELEASE_VERSION` variable to handle cases where `git describe --tags --dirty` returns an empty value.
**Problem**:
In environments like GitHub Actions where tags are not fetched by default, the `RELEASE_VERSION` variable is empty. This causes issues during the startup of the CDC component, as a valid version is required.
**Solution**:
Add a fallback value (`v9.0.0-alpha`) to ensure that `RELEASE_VERSION` is never empty:
•	If `git describe --tags --dirty` returns an empty value, the `RELEASE_VERSION` variable defaults to `v9.0.0-alpha`.
**Test Plan**
1. Local Environment:
* Ensure `git describe --tags --dirty` sets `RELEASE_VERSION` correctly when tags are available.
* Test in a dirty working tree to verify …
=> add fallback value for RELEASE_VERSION in Makefile

cmd/cdc/server/server.go, cmd/kafka-consumer/writer.go, cmd/pulsar-consumer/main.go, logservice/eventstore/event_store.go, logservice/schemastore/persist_storage.go, logservice/schemastore/schema_store.go, pkg/eventservice/event_service.go, pkg/messaging/message_center.go, pkg/messaging/target.go, pkg/messaging/target_test.go, pkg/sink/codec/canal/codec_test.go, pkg/sink/codec/canal/helper.go, server/module_election.go, server/module_grpc.go, server/server.go, server/watcher/module_node_manager.go, tests/integration_tests/_utils/check_logs, tests/integration_tests/availability/capture.sh, tests/integration_tests/availability/owner.sh, tests/integration_tests/availability/run.sh, tests/integration_tests/cli_tls_with_auth/run.sh, tests/integration_tests/cli_with_auth/run.sh, tests/integration_tests/http_api/run.sh, tests/integration_tests/resolve_lock/main.go
Issue Number: ref #442 
```release-note
None
```
=> test: fix a couple of cli it cases

.gitignore, Makefile
Issue Number: close #909
This PR consolidates our scattered unit tests from GitHub Actions into a single Makefile target. Currently, we have 4 separate test jobs in our CI workflow (dispatcher, maintainer, coordinator, and eventservice).
To ensure a more streamlined development process, we are consolidating all unit tests under a single Makefile target, `unit_test_in_verify_ci`. This improvement will result in:
* Simplified CI configuration: Making the setup easier to manage and maintain.
* Unified test reports and coverage: Providing a clearer and more consistent overview of test results.
Key Changes:
- Combine dispatcher, maintainer, coordinator and eventservice unit tests
- Add UT_PACKAGES variables for different test modules
- Standardize timeout to 120s
- Use single gotestsum command …
=> ut, makefile: consolidate unit tests into single makefile target

downstreamadapter/dispatchermanager/event_dispatcher_manager.go, logservice/schemastore/persist_storage.go, tests/integration_tests/capture_session_done_during_task/run.sh, tests/integration_tests/capture_suicide_while_balance_table/run.sh, tests/integration_tests/changefeed_fast_fail/run.sh
Issue Number: close #915 #914 ref #442 
This pull request accomplishes the following:
1. Fixes the integration test case `changefeed_fast_fail`.
```release-note
None
```
=> test: fix intetragion test case `changefeed_fast_fail`

coordinator/changefeed/backoff.go, coordinator/changefeed/changefeed.go, coordinator/changefeed/changefeed_db.go, coordinator/controller.go, coordinator/coordinator_test.go, heartbeatpb/heartbeat.pb.go, logservice/schemastore/persist_storage_ddl_handlers.go, maintainer/maintainer.go, maintainer/maintainer_manager.go, pkg/bootstrap/bootstrap.go, pkg/common/format.go, pkg/common/format_test.go, pkg/common/types.go, pkg/messaging/message_center.go, tests/integration_tests/ddl_attributes/run.sh
Issue Number: close #921 
When reconstructing a changefeed from the meta DB to the coordinator's memory, check whether it is in a warning state. If so, set its backoff state to retrying. 
The core fix is implemented here: 
```go
// Must set retrying to true when the changefeed is in warning state.
if info.State == model.StateWarning {
res.backoff.retrying.Store(true)
}
```
- Unit test
```release-note
None
```
=> coordinator: fix a bug that keep changefeed in warning state

.github/workflows/integration_test_mysql.yaml, logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, pkg/common/event/ddl_event.go, tests/integration_tests/multi_tables_ddl/run.sh
Issue Number: close #805 
- Unit test
- No code
```release-note
```
=> test: enable multi_tables_ddl test

.github/workflows/integration_test_mysql.yaml, downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/sink/mysql_sink_test.go, maintainer/barrier.go, maintainer/barrier_event.go, maintainer/barrier_event_test.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go, pkg/sink/mysql/mysql_writer_for_syncpoint.go, pkg/sink/mysql/mysql_writer_test.go, tests/integration_tests/_utils/run_sql_ignore_error, tests/integration_tests/fail_over_ddl_mix/conf/changefeed.toml, tests/integration_tests/fail_over_ddl_mix/conf/diff_config.toml, tests/integration_tests/fail_over_ddl_mix/run.sh
1. insert ddl ts item before ddl event sent to downstream when downstream is tidb, to fix the atomic corner problem when server crash when ddl event is sent, but ddl ts is not sent.
2. Add a mix random test for ddl failover cases for more completely test
- Unit test
- No code
```release-note
```
=> Use ddl_ts to fix the atomic problem of ddl_ts and ddl event; Add a mix failover test for test ddl failover cases randomly

pkg/sink/mysql/mysql_writer_ddl.go, pkg/sink/mysql/mysql_writer_test.go
Add test to ensure the async ddl `add index` can be deal with correctly, including:
1. the async ddl can be written successfully
2. the dmls will not be blocked by the async ddl
3. the ddl of other tables will not be blocked by the async ddl
4. the ddl of this table will be blocked by the async ddl.
- Unit test
- No code
```release-note
```
=> mysql: fix and add test for async ddl `add index`

logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/utils.go, pkg/common/event/ddl_event.go, pkg/common/event/ddl_event_test.go, pkg/common/event/util.go
1. use parse to split queries
2. split renaming tables
- Unit test
- No code
```release-note
```
=> Fix DDL split events 

README.md
- Unit test
- No code
```release-note
```
=> *: update binary download link in readme

downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go, downstreamadapter/eventcollector/event_collector.go, utils/dynstream/interfaces.go, utils/dynstream/memory_control.go, utils/dynstream/memory_control_test.go, utils/dynstream/parallel_dynamic_stream_test.go
Issue Number: ref #994 
- Unit test
```release-note
None
```
=> DS: refactor memory control module

api/http.go, api/v1/api.go, api/v2/api.go, api/v2/capture.go, api/v2/changefeed.go, api/v2/coordinator.go, api/v2/health.go, api/v2/helper.go, api/v2/log.go, api/v2/processor.go, api/v2/status.go
Issue Number: ref #989 
Add all v1 HTTP APIs.
```release-note
None
```
=> api: add HTTP API v1

downstreamadapter/eventcollector/event_collector.go, maintainer/replica/checker.go, metrics/grafana/ticdc_new_arch.json, pkg/common/event/ddl_event.go, pkg/common/event/handshake_event.go, pkg/common/event/interface.go, pkg/common/event/ready_event.go, pkg/common/event/resolved_ts_event.go, pkg/common/event/sync_point_event.go
Modify the metric unit in the `EventService output events / s` panel from `event/s` to `row/s` to align with other panels in the `Dataflow` row.
- No code
```release-note
None
```
=> metrics: unify the metrics in dataflow to rows/s

pkg/sink/codec/canal/encoder.go, tests/integration_tests/canal_json_storage_partition_table/conf/diff_config.toml
Issue Number: ref #442
add columnSelector field to avoid panic
- Unit test
```release-note
`None`.
```
=> test: fix canal_json_storage test

maintainer/maintainer.go, maintainer/maintainer_test.go
Issue Number: ref #1030 
As title.
- No code
```release-note
None
```
=> maintainer: use ticker to generate periodEvent

tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1033
This PR fixes a typo in the run_light_it_in_ci.sh where charset_gbk was mistakenly written as chartset_gbk. This issue caused integration tests to fail due to missing directories and files.
```release-note
None
```
=> ci: fix typo in run_light_it_in_ci.sh (chartset_gbk → charset_gbk)

tests/integration_tests/_utils/check_coverage.sh
Issue Number: close #1050
This PR modifies the check_test_coverage function to prevent the script from failing when missing test cases are found. Since we are still adding tests, it is expected that some test cases will be missing. Instead of failing CI, the script will now only display a warning.
- No code
No.
No.
```release-note
None
```
=> ci: remove check_coverage.sh exit before all missing test added

coordinator/changefeed/changefeed.go, coordinator/changefeed/changefeed_db_test.go, coordinator/changefeed/changefeed_test.go, coordinator/controller_test.go, coordinator/coordinator.go, pkg/sink/cloudstorage/path_test.go, pkg/sink/codec/csv/csv_message.go
Issue Number: ref #442
1. add checkpointTs message for storage sink
2. fix incorrect operation type about csv
- Unit test
```release-note
`None`.
```
=> sink: add checkpointTs message for storage sink

coordinator/controller.go, coordinator/coordinator.go, coordinator/helper.go
Issue Number: ref #442
change changefeed state is ahead of sending checkpointTs message in the past. This makes no checkpointTs message if the state is finished. 
Kafka consumer depends on checkpointTs messages to write previous DDL/DML events.
- Unit test
```release-note
`None`.
```
=> coordinator: send checkpointTs message when changefeed state is finished

Makefile
Issue Number: close #1075
This PR adds a prepare_test_binaries target to the Makefile, allowing users to easily download TiCDC-related binaries for integration testing using a single make command.
Usage:
```
make prepare_test_binaries
```
To specify a version, OS, or architecture, use:
```
make prepare_test_binaries community=true ver=v8.0.0 os=linux arch=amd64
```
- Manual test
```
make prepare_test_binaries
```
No.
No.
```release-note
None
```
=> makefile: add prepare_test_binaries target to Makefile

tests/integration_tests/cli_tls_with_auth/run.sh
Issue Number: close #1077
Remove the check for enable_table_across_nodes being true for the MySQL type in the integration test cli_tls_with_auth.
No.
No.
```release-note
None
```
=> cli_tls_with_auth: enable_table_across_nodes should be true in mysql after supported

logservice/logpuller/subscription_client.go
Issue Number: close #1081
1. We have limited go routines to schedule range request, and they may be blocked on lock ranges.
2. These ranges may be locked by other stale regions, and the ranges can only be unlocked by` doHandleError`.
3. `doHandleError` may blocked on sending `rangeTask`, because all the go routines are blocked on lock ranges and cannot handle the new `rangeTask`.
- Unit test
- No code
```release-note
```
=> puller: fix dead lock

tests/integration_tests/cli_with_auth/run.sh
Issue Number: close #1082
Remove the check for enable_table_across_nodes being true for the MySQL type in the integration test cli_with_auth.
No.
No.
```release-note
None
```
=> cli_with_auth: enable_table_across_nodes should be true in mysql after supported

tools/workload/main.go, tools/workload/schema/bank/bank.go, tools/workload/schema/bank2/bank2.go, tools/workload/schema/bankupdate/bank_update.go, tools/workload/schema/bankupdate/readme.md, tools/workload/schema/largerow/large_row.go, tools/workload/schema/shop/shop.go, tools/workload/schema/sysbench/sysbench.go, tools/workload/schema/update_bank.go, tools/workload/schema/uuu/uuu.go, tools/workload/util/util.go
Issue Number: close #1111 
Add an update_bank workload, which can write data upstream at a rate of several GB per second.
The following is the command to use this workload.
```
./workload -database-host 10.128.15.221 -database-port 4000  -action prepare -database-db-name test -table-count 1 -workload-type bank_update -thread 16 -total-row-count 20000000  -update-large-column-size 4000
./workload -database-host 10.128.15.221 -database-port 4000 -action update -database-db-name test -table-count 1 -workload-type bank_update -thread 16 -total-row-count 20000000 -percentage-for-update 1.0 -batch-size 20000 -update-large-column-size 4000
```
```release-note
None
```
=> workload: add a high throughput workload for testing. 

pkg/errors/error.go, tests/integration_tests/_utils/check_contains, tests/integration_tests/_utils/check_logs, tests/integration_tests/_utils/check_not_contains, tests/integration_tests/_utils/run_sql, tests/integration_tests/_utils/run_sql_file, tests/integration_tests/_utils/run_sql_ignore_error, tests/integration_tests/region_merge/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh, tests/integration_tests/run_light_it_in_ci.sh, tests/integration_tests/syncpoint/run.sh, tests/integration_tests/syncpoint_check_ts/run.sh
Issue Number: close #1119 
Move region_merge to the heavy group since it always encounters the error of SQL execution timeout.
Change the output files with the .txt suffix produced by the integration test to .log so that they can be uploaded to Artifacts for debugging. 
```release-note
None
```
=> tests: fix `region_merge` case.

cmd/cdc/main.go, cmd/cdc/server/server.go, go.mod, go.sum
Issue Number: close #1134
This PR ensures that the TiCDC binary always uses the new architecture client. Previously, the binary defaulted to the old architecture client, which could cause errors due to missing configurations when running with the new architecture. Since the new architecture client is fully compatible with the old architecture, using it exclusively avoids these issues while maintaining backward compatibility.
* Binary Modification: The TiCDC binary now always uses the new architecture client
* cdc server Behavior Unchanged: The cdc server command still defaults to the old architecture but allows users to switch to the new architecture using:
* `--newarch` or `-x` flag
* Setting `TICDC_NEWARCH=true`
* Adding `newarch: true` in the server configuration
This change ensures …
=> *: modify cdc binary to always use new arch client except `cdc server`

logservice/schemastore/disk_format.go, logservice/schemastore/multi_version.go, logservice/schemastore/multi_version_test_utils.go, logservice/schemastore/persist_storage.go, logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/persist_storage_test_utils.go, logservice/schemastore/types.go
Issue Number: close #1142 
When schema store starts, it will fetch a snapshot of table info from upstream. And these infos are stored on disk in the format `logical_table_id -> table_info`. 
When we receive a dispatcher register request, we only knows the physical table id of the dispatcher. And we cannot fetch the table info from disk using the physical table id for partition tables. So we need a way to get the logical table id of the physical table id.
This pr writes an entry for every physical partition in the format `physical_table_id -> logical_table_id`.
When we receive a dispatcher register request, we will fetch the table info in the following steps:
1. use the table id of the dispatcher to get the table info directly;
2. if fail to get table info, try use the table id as the key …
=> schemastore: fix register partition table

downstreamadapter/sink/conflictdetector/helper.go, downstreamadapter/sink/helper/eventrouter/partition/columns.go, downstreamadapter/sink/helper/eventrouter/partition/index_value.go, pkg/common/event/dml_event.go, pkg/common/event/mounter_test.go, pkg/common/event/redo.go, pkg/common/event/row_change.go, pkg/common/helper.go, pkg/common/table_info.go, pkg/sink/mysql/mysql_writer_helper.go, pkg/sink/mysql/sql_builder.go
Issue Number: close #1188 
* Replaces common.FormatColVal with common.ExtractColVal in multiple modules.
* Removes unused code including the SchemaID field in TableInfo and the GetColumnDefaultValue function.
* Standardizes variable naming (e.g., rowType instead of RowType) for consistency.
- Unit test
```release-note
`None`
```
=> *: adjust some code and remove unused code

downstreamadapter/dispatchermanager/heartbeat_collector.go, pkg/messaging/target.go, server/module_grpc.go, utils/conn/helper.go
Issue Number: ref #1151 
This PR will make gRPC connection between cdc nodes more stable through the following changes:
1. Only reset gRPC stream when receiving a error from remote node instead of resetting the gRPC connection. 
2. Add keep-alive options for both the gRPC client and server to make gRPC  connection more stable. 
```release-note
None
```
=> messaging: fix error

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/sink/blackhole.go, downstreamadapter/sink/cloudstorage.go, downstreamadapter/sink/cloudstorage_test.go, downstreamadapter/sink/conflictdetector/conflict_detector.go, downstreamadapter/sink/conflictdetector/helper.go, downstreamadapter/sink/helper/eventrouter/partition/columns.go, downstreamadapter/sink/helper/eventrouter/partition/index_value.go, downstreamadapter/sink/kafka_sink.go, downstreamadapter/sink/kafka_sink_test.go, downstreamadapter/sink/mysql_sink.go, downstreamadapter/sink/pulsar_sink.go, downstreamadapter/sink/pulsar_sink_test.go, downstreamadapter/sink/sink.go, pkg/common/event/mounter_test.go, pkg/common/event/redo.go, pkg/common/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_helper.go, pkg/sink/mysql/sql_builder.go, pkg/sink/mysql/sql_builder_benchmark_test.go, pkg/sink/mysql/sql_builder_test.go
Issue Number: close #1205
* Removed error propagation from helper functions (e.g. getArgs, whereSlice, ExtractColVal) so that errors trigger a panic immediately.
* Updated API signatures (e.g. AddDMLEvent, generate* functions) by eliminating error returns, with corresponding updates in call sites.
* Adjusted unit tests to remove error checking on extraction functions.
- Unit test
```release-note
`None`
```
=> mysql: extract col value meet error then panic immediately

downstreamadapter/sink/conflictdetector/helper.go, downstreamadapter/sink/mysql_sink.go, downstreamadapter/worker/mysql_worker.go, pkg/common/event/dml_event.go, pkg/common/event/redo.go, pkg/sink/codec/simple/encoder_test.go, pkg/sink/mysql/config.go, pkg/sink/mysql/config_test.go, pkg/sink/mysql/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_ddl.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go, pkg/sink/mysql/mysql_writer_for_syncpoint.go, pkg/sink/mysql/mysql_writer_test.go, pkg/sink/mysql/sql_builder.go
Issue Number: close #1215 
* Renaming from FinishGetRow to Rewind provides a clearer description of the function's purpose. Ensure that documentation and any external references are updated accordingly.
* remove the prefix mysql from some structs
```release-note
`None`
```
=> mysql: rename some struct to make it less verbose

pkg/sink/codec/open/codec.go, pkg/sink/codec/open/decoder.go, pkg/sink/codec/open/encoder.go, pkg/sink/codec/open/encoder_test.go, pkg/sink/codec/open/message.go
Issue Number: close #1227 
* Changing the column Flag type from uint to uint64 and updating related flag-check calls to use new helper functions (e.g. isBinary, isUnsigned, isPrimary).
* Introducing a column flags caching mechanism in the batch encoder to improve flag calculation efficiency.
* Adjusting encoding and decoding logic to properly pass the computed column flags.
- Unit test
```release-note
`None`
```
=> codec: fix the open protocol flag

cmd/storage-consumer/main.go, downstreamadapter/sink/cloudstorage.go, downstreamadapter/sink/helper/helper.go, downstreamadapter/worker/cloudstorage_ddl_worker_test.go, downstreamadapter/worker/cloudstorage_dml_worker_test.go, downstreamadapter/worker/writer/writer_test.go, pkg/redo/config.go, pkg/sink/cloudstorage/path_test.go, pkg/sink/codec/open/encoder_test.go, pkg/util/external_storage.go, pkg/util/external_storage_test.go, pkg/util/tz_test.go
Issue Number: close #1239
- Unit test
```release-note
```
=> cloudstorage: fix a bug that may cause changefeed getting stuck

downstreamadapter/sink/eventrouter/event_router.go, downstreamadapter/sink/eventrouter/event_router_test.go, downstreamadapter/sink/eventrouter/partition/generator.go, downstreamadapter/sink/eventrouter/topic/expression.go, downstreamadapter/sink/eventrouter/topic/topic.go, downstreamadapter/sink/kafka/helper.go, downstreamadapter/sink/kafka/sink.go, downstreamadapter/sink/pulsar/helper.go, downstreamadapter/sink/pulsar/sink.go
Issue Number: close #1289 
* Updating the NewEventRouter, GetTopicForRowChange, and GetPartitionGenerator interfaces to accept explicit parameters.
* Refactoring both Pulsar and Kafka sinks to use the simplified event router interface.
* Adjusting test cases to align with the new method signatures.
- Unit test
```release-note
`None`
```
=> sink: simplify the event router method interface

downstreamadapter/sink/cloudstorage/defragmenter_test.go, downstreamadapter/sink/cloudstorage/sink.go, downstreamadapter/sink/helper/helper.go, downstreamadapter/sink/kafka/helper.go, downstreamadapter/sink/kafka/sink.go, downstreamadapter/sink/pulsar/helper.go, downstreamadapter/sink/pulsar/sink.go, maintainer/maintainer.go, maintainer/maintainer_controller.go, pkg/common/columnselector/column_selector.go, pkg/common/columnselector/column_selector_test.go, pkg/sink/codec/canal/canal_json_test.go, pkg/sink/codec/open/encoder_test.go, pkg/sink/util/helper.go
Issue Number: close #1291 
* Moved the GetEncoderConfig function to downstreamadapter/sink/helper and updated all call sites.
* Refactored columnselector API calls from NewColumnSelectors/GetSelector to New/Get.
* Updated comment and variable naming related to MySQL compatibility.
- Unit test
- No code
```release-note
`None`
```
=> sink: move some helper method to the caller package

pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_dml.go
Issue Number: close #1298 
* Changing the event grouping key from dispatcherID to table ID in pkg/sink/mysql/mysql_writer_dml.go.
* Simplifying batch SQL generation by using variadic appends.
* Streamlining error handling and callback invocation in pkg/sink/mysql/mysql_writer.go.
- Unit test
```release-note
`None`
```
=> mysql: group multiple dml events by the table id instead of the dispatcher id

api/v2/api.go, api/v2/changefeed.go, cmd/cdc/cli/cli_changefeed.go, cmd/cdc/cli/cli_changefeed_move_split_table.go, downstreamadapter/dispatcher/dispatcher.go, maintainer/barrier_event.go, maintainer/maintainer.go, maintainer/maintainer_controller.go, maintainer/scheduler/split.go, pkg/api/v2/changefeed.go, pkg/api/v2/mock/changefeed_mock.go, pkg/sink/mysql/helper.go, tests/integration_tests/_utils/move_split_table_with_retry, tests/integration_tests/ddl_for_split_tables_with_random_move_table/conf/changefeed.toml, tests/integration_tests/ddl_for_split_tables_with_random_move_table/conf/diff_config.toml, tests/integration_tests/ddl_for_split_tables_with_random_move_table/data/pre.sql, tests/integration_tests/ddl_for_split_tables_with_random_move_table/run.sh, tests/integration_tests/ddl_with_random_move_table/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
1. add a move-split-table api to move all dispatchers in a split-table to a target node, which is useful in making test cases
2. make a test to ensure the ddl and dml can be correctly dealing with, under frequently scheduling actions of moving dispatchers.
3. fix a bug of querying downstream DDL execution status sql statement
4. fix a bug to ensure dml events will not go into dispatcher when the previous ddl event not finished.
- Unit test
- No code
```release-note
If you don't think this PR needs a release note then …
```
=> fix some bugs in dispatcher and add test for random ddl with random moving dispatchers in the splitted tables

pkg/sink/codec/debezium/decoder.go, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1087
- Unit test
```release-note
`None`.
```
=> codec: fix debezium decoder

metrics/grafana/ticdc_new_arch.json
1. make `Ouptut Row Batch Size` panel show data correctly
2. remove two useless panel `DML Event Size Heatmap` and `Large Row (size >= 128K) Size`
- Unit test
- No code
```release-note
```
=> metrics: correct some metrics and remove useless panel 

pkg/sink/mysql/config.go, pkg/sink/mysql/helper.go, pkg/sink/mysql/mysql_writer_ddl.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go
- Unit test
- No code
```release-note
```
=> sink: set `tidb_cdc_write_source` in dsn instead of set session variable seperately before each txn 

pkg/common/table_info_helper.go, pkg/common/table_info_helper_test.go
Issue Number: close #1184
`HandleKeyIDs` was introduced by https://github.com/pingcap/ticdc/pull/1185, there exists a bug when the primary key is not a single integer column.
- Unit test
```release-note
`None`.
```
=> *: correct handle key in table info

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/sink/mock_sink.go
when dispatcher receive a batch dml events, we need to add these all dml events into tableProgress first, and then add them to sink, in order to ensure the wakeCallback only happen when all these events flushed successfully.
- Unit test
- No code
```release-note
```
=> dispatcher: fix bug in wakeCallback

downstreamadapter/eventcollector/event_collector_test.go, pkg/common/event/handshake_event.go, pkg/common/event/handshake_event_test.go, pkg/eventservice/dispatcher_stat.go, pkg/eventservice/dispatcher_stat_test.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_broker_test.go, pkg/eventservice/event_scanner.go, pkg/eventservice/event_scanner_test.go, pkg/eventservice/metrics_collector.go
Issue Number: ref #1328
In the original implementation, `checkNeedScan` would return false if the handshake event hadn't been sent, meaning data events could only be transmitted after receiving the next resolved ts event. This behavior introduced an unavoidable latency of at least one `min-ts-interval` during operations like dispatcher scheduling, splitting, or merging.
However, we can optimize this workflow:
Data events can be safely transmitted immediately after sending the handshake event, provided we strictly maintain the event ordering guarantee that the handshake event precedes all subsequent data events.
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style …
```
=> eventboker: send data events immediately after handshake event

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/eventcollector/helper.go
* **Event Batching Optimization**: Resolved timestamp (resolvedTs) events and Data Manipulation Language (DML) events are now grouped into a single data group (`DataGroupResolvedTsOrDML`). This change aims to prevent DML batches from becoming too small due to frequent resolvedTs events, thereby improving the overall performance of the sink by allowing for more efficient batching.
* **Correct Resolved Timestamp Update Order**: The update of the `resolvedTs` in the `Dispatcher` is now deferred. Instead of updating it immediately upon receiving a `TypeResolvedEvent`, the timestamp is temporarily stored and then applied *after* all DML events in the current batch have been added to the sink. This critical reordering prevents potential issues where the `checkpointTs` …
=> eventCollector: allow resolvedTs and dml event in the same batch

downstreamadapter/dispatcher/basic_dispatcher.go, tests/integration_tests/_utils/check_logs
* **Log Level Adjustment**: I've observed that the log level for the `HandleDispatcherStatus` function in `downstreamadapter/dispatcher/basic_dispatcher.go` has been degraded from `log.Info` to `log.Debug`. This change aims to reduce the verbosity of the logs.
- Unit test
- No code
```release-note
```
=> log: degrade the log level to avoid too many useless log

pkg/config/changefeed.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1541
**Error Message Truncation**: Implemented logic within the ChangeFeedInfo.Marshal() method to truncate long error messages. If an error message exceeds 100 characters, it will be cut down to 100 characters, with '...' appended, before being marshaled into JSON.
**Etcd Resource Management**: This change directly addresses the ResourceExhausted error that can occur when attempting to store excessively long error messages in etcd, ensuring more stable and reliable interaction with the etcd key-value store.
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/rele …
```
=> coordinator: cut down the long error message info to avoid error `ResourceExhausted` occurs when interacting with etcd

cmd/kafka-consumer/event_group.go, cmd/pulsar-consumer/event_group.go, downstreamadapter/sink/cloudstorage/dml_writers.go, downstreamadapter/sink/redo/sink.go, pkg/common/event/dml_event.go, pkg/common/kv_entry.go, pkg/eventservice/event_scanner.go, pkg/eventservice/event_scanner_test.go, pkg/metrics/event_service.go, pkg/sink/codec/canal/canal_json_txn_decoder.go, pkg/sink/mysql/mysql_writer_dml.go
Issue Number: close #1591
* RawEntry size also + 40 bytes, for other length fields.
* DMLEvent and BatchDMLEvent size is calculated by using the chunk provided memory usage method. Compare to previous implementation based on the raw entry size, it's more accurate, enlarged around 50% according to the test.
- Unit test
```release-note
`None`
```
=> event: dml size correctly calculated by using the chunk memory usage method instead of the raw entry size

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/event_collector.go, logservice/eventstore/event_store.go
Issue Number: close #1605 
- Enhanced Message Retry Logic: I've refactored the message retry mechanism within the event collector to distinguish between local and remote messages. Local messages will now retry indefinitely, ensuring critical internal communications are not dropped, while remote messages will adhere to a defined retry quota.
- Dynamic Retry Backoff: I've introduced dynamic sleep intervals for message retries. Specifically, if a message send fails due to congestion, the system will now wait for a longer period (1 second) before retrying, helping to alleviate pressure on the system.
- Improved Dispatcher Registration Logging: I've added a new logging mechanism to warn when a dispatcher is registered with a startTs that is significantly behind the current PD time, which can …
=> eventcollector: avoid drop local messages

cmd/cdc/server/server.go, logservice/logpuller/region_event_handler.go
Issue Number: close #1621 
When start the server, set the `TiKV.MaxBatchSize` to 0, since it's not used by the ticdc server, also may not support by other upstream components.
- Unit test
- No code
```release-note
`None`.
```
=> cmd: patch tidb config set tikvclient max batch size to 0

cmd/cdc/factory/factory.go
Issue Number: close #1631
Fixed a typo in the help message displayed when running the `/cdc cli help` command.
- No code
Nothing.
No.
Yes (CLI's help), but just only fixing a typo.
```release-note
None
```
=> cli: fix typo in the help message for the --user flag

logservice/coordinator/coordinator.go, logservice/coordinator/coordinator_test.go
Issue Number: close #1642
**Node Filtering Logic**: The getCandidateNodes function now includes a check to ensure that only active and healthy nodes (those present and not nil in c.nodes.m) are considered when building the list of potential candidates for data retrieval.
- Unit test
- No code
```release-note
```
=> logcoordinator: ignore down nodes

pkg/filter/filter.go, pkg/filter/filter_test.go, pkg/messaging/message.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1677
*   **New `FilterWithConfig` struct:** This struct encapsulates the `Filter` interface along with the `eventpb.FilterConfig` and `timeZone` string, providing a complete context for each stored filter.
*   **Enhanced `GetOrSetFilter` logic:** The method now performs a deep comparison of the incoming filter configuration and timezone against the stored ones. It leverages a new helper function, `isFilterConfigEqual`, which uses `proto.Equal` for robust comparison of protobuf messages.
*   **Conditional Filter Rebuilding:** A filter is now only rebuilt if its configuration or timezone has genuinely changed, preventing unnecessary re-initializations.
*   **Updated Call Site:** The `GetFilter()` method in …
=> filter: Fix sharing filter after update config

logservice/schemastore/persist_storage_test.go
Issue Number: close #1899
This PR fixes a flaky unit test, `TestApplyDDLJobs`, which was failing due to an incorrect comparison between expected and actual results.
The test sorts several slices within the `expected` struct but did not sort the corresponding slices in the `actual` struct returned by the function. Since the order of elements in these slices is not guaranteed, the `reflect.DeepEqual` comparison would fail whenever the actual order did not match the expected sorted order, making the test unreliable.
This change introduces sorting for the `actual` result slices to mirror the sorting applied to the `expected` result slices, ensuring the test is deterministic and only checks for content equality.
**Detailed changes:**
- Sorts `actualDDLEvent.UpdatedSchemas` by `TableID`.
- …
=> fix(test): sort actual results in TestApplyDDLJobs for stable comparison

pkg/filter/filter.go, pkg/filter/filter_test.go, pkg/filter/sql_event_filter.go, pkg/filter/sql_event_filter_test.go
Issue Number: close #1809
This PR fixes a bug where the event filter feature was ignoring the global `case-sensitive` configuration and always performing case-sensitive table matching.
**Changes:**
1.  **Propagate `caseSensitive` Flag:** The `caseSensitive` boolean is now passed through the filter creation chain: `NewFilter` -\> `newSQLEventFilter` -\> `newSQLEventFilterRule`. This ensures the SQL event filter is aware of the global case sensitivity setting.
2.  **Conditional Case-Insensitive Matching:** In `newSQLEventFilterRule`, the `tfilter` is now conditionally wrapped with `tfilter.CaseInsensitive(tf)` only when `caseSensitive` is `false`. When `true`, the default case-sensitive `tfilter` is used, achieving the desired behavior.
3.  **Refactor and Add Testing:**
* Removed a …
=> fix(filter): ensure event filter respects case-sensitive setting

maintainer/replica/split_span_checker.go, maintainer/scheduler/balance_splits.go, pkg/scheduler/replica/replication.go, tests/integration_tests/_utils/query_dispatcher_count, tests/integration_tests/ddl_for_split_tables_random_schedule/conf/changefeed.toml, tests/integration_tests/ddl_for_split_tables_random_schedule/conf/diff_config.toml, tests/integration_tests/ddl_for_split_tables_random_schedule/data/pre.sql, tests/integration_tests/ddl_for_split_tables_random_schedule/run.sh, tests/integration_tests/ddl_for_split_tables_with_failover/run.sh, tests/integration_tests/ddl_for_split_tables_with_merge_and_split/run.sh, tests/integration_tests/ddl_for_split_tables_with_random_merge_and_split/run.sh, tests/integration_tests/ddl_for_split_tables_with_random_move_table/run.sh, tests/integration_tests/merge_table/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
- Unit test
- No code
```release-note
```
=> scheduler: fix bugs to make scheduler more robust

pkg/util/external_storage.go, pkg/util/external_storage_test.go
cherry pick https://github.com/pingcap/tiflow/pull/12276 from tilflow
- Unit test
- No code
```release-note
```
=> cherry pick `cloudstorage: fix a bug causing context cancelled errors and stuck sink`

logservice/logpuller/priority_queue.go, logservice/logpuller/priority_queue_test.go
Issue Number: close #2120 
Don't close the `p.signal` channel when closing the queue. 
- Unit test
```release-note
None
```
=> logpuller: fix a data race in priority queue

logservice/eventstore/event_store.go, logservice/eventstore/event_store_test.go
Issue Number: close #2168
Robust Subscription Management: Introduced a new Subscriber struct and a removingSubStat field within dispatcherStat to manage the lifecycle of subscriptions more robustly, especially during transitions.
Graceful Subscription Switching: Implemented a mechanism to gracefully switch a dispatcher's active subscription from a broader one to a more specific one, ensuring no data gaps and preventing panics by temporarily retaining the old subscription as removingSubStat.
Controlled Event Notification: Added an isStopped flag to the Subscriber struct and a stopReceiveEventFromSubStat function to prevent dispatchers from receiving resolved timestamp events from subscriptions that are being phased out.
Enhanced Error Handling: Refined the GetIterator logic with stricter …
=> eventstore: fix cannot find subStat panic

maintainer/barrier_event_test.go, maintainer/maintainer_controller_bootstrap.go, maintainer/replica/default_span_split_checker.go, maintainer/span/span_controller.go
Issue Number: close #2196 
* **Data Race Prevention (Span Replication)**: Introduced defensive copying of `Span` objects during the creation of span replications to prevent concurrent modification issues and ensure thread safety.
* **Data Race Prevention (KeyspaceID Assignment)**: Removed a potentially racy assignment of `KeyspaceID` to shared `Span` objects within the `AddWorkingSpans` function, eliminating a source of concurrency bugs.
* **Code Simplification**: Streamlined map deletion logic in `default_span_split_checker.go` by removing redundant `if _, ok` checks, as Go's `delete` operation is safe for non-existent keys.
* **Test Refinement**: Updated test cases in `barrier_event_test.go` to use named fields for `heartbeatpb.Table` initialization, improving code readability and …
=> maintainer: fix data race

coordinator/changefeed/etcd_backend.go, coordinator/changefeed/etcd_backend_test.go, coordinator/controller.go, coordinator/coordinator_test.go, logservice/schemastore/schema_store.go, pkg/common/event/mounter.go, pkg/common/types.go, pkg/eventservice/event_broker_test.go, pkg/eventservice/event_scanner_test.go, pkg/eventservice/event_service_test.go, pkg/eventservice/test_helper.go
This PR addresses several issues related to the robustness and correctness of changefeed and keyspace management within TiCDC.
Previously, the extraction of changefeed and keyspace information from etcd keys was fragile, relying on fixed array indices which could break if the key path structure changed. This could lead to incorrect parsing of changefeed metadata.
Additionally, keyspaces associated with existing changefeeds were not automatically registered in the schema store during TiCDC bootstrap, potentially causing issues with schema management for these keyspaces.
Finally, keyspace validation was inconsistent, using a custom regex rather than a standard TiDB utility.
Issue Number: close #2186 #2191 #2194
This PR significantly improves the reliability of etcd key parsing for …
=> Improve changefeed keyspace management by refactoring etcd key extraction and registering all active keyspaces.

logservice/schemastore/schema_store.go, pkg/eventservice/dispatcher_stat.go, pkg/eventservice/dispatcher_stat_test.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_broker_test.go, pkg/eventservice/event_scanner_test.go, pkg/eventservice/metrics_collector.go, pkg/eventservice/test_helper.go
Issue Number: ref #2139
* **Metric Renaming and Clarification**: The `eventStoreResolvedTs` field in `dispatcherStat` has been renamed to `receivedResolvedTs` to more accurately reflect that it tracks resolved timestamps received from both the event store and the schema store.
* **Schema Store Integration**: The `FetchTableTriggerDDLEvents` function in the `SchemaStore` interface and its implementation now accept a `dispatcherID` parameter, allowing for more specific tracking and logging related to individual dispatchers.
* **Correct Resolved Timestamp Updates**: The `receivedResolvedTs` metric is now correctly updated with the `endTs` returned after fetching DDL events from the schema store, ensuring the metric reflects the latest processed timestamp from all relevant sources.
- Unit …
=> eventborker: update wrong received resolved ts metrics

downstreamadapter/dispatchermanager/heartbeat_collector.go, utils/dynstream/parallel_dynamic_stream.go, utils/dynstream/parallel_dynamic_stream_test.go, utils/dynstream/stream.go, utils/dynstream/stream_bench_test.go, utils/dynstream/stream_test.go
Issue Number: close #2217 
```
go test -bench=BenchmarkChannel -benchmem ./utils/dynstream/
goos: darwin
goarch: arm64
pkg: github.com/pingcap/ticdc/utils/dynstream
cpu: Apple M4 Max
BenchmarkChannelDirectSend-14                                   38532294                30.59 ns/op            0 B/op          0 allocs/op
BenchmarkChannelDirectSendHighContention-14                      7781707               162.4 ns/op             0 B/op          0 allocs/op
BenchmarkChannelOptimizedWithContext-14                         39117944                35.40 ns/op            0 B/op          0 allocs/op
BenchmarkChannelOptimizedWithContextHighContention-14            5897019               205.1 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/pingcap/ticdc/utils/dynstream …
```
=> DS: fix a data race that may cause PANIC

coordinator/controller.go, metrics/grafana/ticdc_new_arch.json, pkg/config/changefeed.go, pkg/metrics/changefeed.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2289
To ensure clear monitoring information when a changefeed experiences an abnormal state, we've added two new metrics to the summary: changefeed status and changefeed checkpoint lag. Changefeed checkpoint lag metrics are regularly updated by the coordinator and are therefore unaffected by maintainer status. Even if a changefeed anomaly prevents maintainer creation, the changefeed checkpoint lag metrics will still display normally.
- Unit test
- No code
```release-note
If you don't …
```
=> metrics: Added checkpointTs lag reported by the coordinator

cmd/cdc/cli/cli_changefeed_create.go, cmd/cdc/cli/cli_changefeed_pause.go, logservice/schemastore/schema_store.go, logservice/txnutil/lock_resolver.go, maintainer/testutil/test_util.go, pkg/common/span_op.go, pkg/errors/error.go, pkg/eventservice/event_broker.go, pkg/keyspace/keyspace_manager.go, pkg/pdutil/api_client.go
This PR addresses the issue where components like the schema store and lock resolver might fail to retrieve keyspace metadata if the local cache does not contain it, especially on non-maintainer nodes or during initial setup. Previously, this could lead to `ErrInvalidKeyspace` or other failures when a keyspace was not locally registered, hindering operation in multi-keyspace environments.
Issue Number: close #2292, close #2213, close #2295
This PR introduces several changes to enhance keyspace metadata retrieval and management, enabling dynamic fetching from PD when needed:
* **Dynamic Keyspace Retrieval and Registration in SchemaStore**:
* The `getKeyspaceSchemaStore` function in `logservice/schemastore/schema_store.go` is modified to dynamically fetch and register a keyspace if it's not …
=> Register keyspace when it was not found in the schema cache

logservice/schemastore/persist_storage.go, logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/persist_storage_test_utils.go, pkg/common/table_info.go
Issue Number: close #2284
This fix ensures that the DDL event for the non-partitioned table correctly contains its schema as it existed immediately *before* the exchange operation, which is the behavior backend component expect.
- Unit test
None
None
```release-note
None
```
=> fix(ddl): use correct table info for exchange partition ddl

logservice/schemastore/ddl_job_fetcher.go, logservice/schemastore/persist_storage.go, logservice/schemastore/persist_storage_ddl_handlers.go, pkg/common/event/mounter.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_dml_test.go
Issue Number: close #2288 
1. **Incomplete DDL Filtering in SchemaStore**  
In the `schemaStore.handleDDLJob()` method, certain DDLs are filtered out via `filter.ShouldDiscardDDL()`. These filtered DDLs are not delivered to the `eventBroker`, but the `tableInfo` is still updated—leading to changes in `tableInfo.updateTs`.  
2. **Batch Splitting by `eventBroker` Based on `updateTs`**  
When scanning events, the `eventBroker` splits `batchDML` into different batches according to DDLs and `tableInfo.updateTs`. Even if no actual DDL events are delivered, the change in `updateTs` still results in multiple `batchDML`s with different `updateTs` values.  
3. **Regrouping by Dispatcher**  
After receiving `batchDML`, the `dispatcher` splits it into multiple `dmlEvent`s. Without intermediate DDLs, …
=> mysql: group events by tableInfo updateTs 

tests/integration_tests/restart_changefeed/conf/diff_config.toml, tests/integration_tests/restart_changefeed/run.sh
This PR addresses the need for robust integration tests to verify TiCDC's behavior during server restarts. Specifically, it ensures that changefeeds maintain their correct state (normal or stopped) and resume data synchronization successfully after a TiCDC server process is killed and restarted. This helps to confirm the fault tolerance and stability of the changefeed mechanism.
Issue Number: close #2315
This PR introduces a new integration test suite `restart_changefeed` to validate TiCDC's resilience to server restarts.
The changes include:
* **Added `tests/integration_tests/restart_changefeed/conf/diff_config.toml`**: A new configuration file for `sync_diff` to specify the tables and instances for data consistency checks within the new test.
* **Added …
=> tests: Add integration test to validate changefeed state persistence across CDC server restarts, including paused and active states.

tests/scripts/download-integration-test-binaries-macos.sh
Running integration tests on macOS currently requires manually downloading and setting up various binaries (TiDB components, Kafka, MinIO, etc.). This PR addresses this by providing an automated script to download all necessary integration test binaries for macOS users, simplifying the setup process and ensuring consistency across developer environments.
Issue Number: close #2231
A new shell script `tests/scripts/download-integration-test-binaries-macos.sh` has been added. This script automates the download and setup of all external binaries required to run TiCDC integration tests on macOS.
* The script downloads essential tools: `minio`, `jq`, `confluent`, `go-ycsb`, `etcdctl`, and `sync_diff_inspector`.
* It downloads TiDB components: `tidb`, `tikv`, `cdc`, `pd`, `tiflash`, and `ctl` …
=> Add a script to download integration test binaries for macOS to simplify the setup of integration test environments.

logservice/logpuller/region_event_handler.go
Issue Number: ref #2387
cse support prewrite not sent, always send committed entry, first round test passed, so remove this workaround.
- Unit test
```release-note
`None`
```
=> matcher: revert report error if matcher cannot found prewrite in the next-gen mode

logservice/eventstore/event_store.go, logservice/eventstore/event_store_test.go
Issue Number: close #2458 
* **Concurrency Model Overhaul**: Replaced a mutex-protected map of subscribers with an "atomic.Pointer" holding a "subscribersWithIdleTime" struct, enabling lock-free concurrent management of dispatchers.
* **Deadlock Mitigation**: The shift from mutex-based locking to atomic operations directly addresses and prevents potential deadlocks that could occur during frequent updates and notifications to dispatchers.
* **Streamlined Subscriber State**: The "isStopped" field in the "Subscriber" struct was simplified from "atomic.Bool" to a plain "bool", as its state is now managed within the atomically updated subscriber map.
* **Atomic Map Operations**: Introduced a new helper "addSubscriberToSubStat" and refactored existing functions ("RegisterDispatcher", …
=> eventstore&eventbroker: fix dead lock

logservice/eventstore/event_store.go, metrics/grafana/ticdc_new_arch.json, pkg/metrics/event_store.go
Issue Number: ref #2409
* **New Metric Introduced**: A new Prometheus histogram metric, `EventStoreRegisterDispatcherStartTsLagHist`, has been added to measure the lag of `startTs` when a dispatcher is registered in the event store.
* **Metric Observation**: The `event_store.go` file now records the calculated `startTs` lag into the newly defined histogram metric during dispatcher registration.
* **Grafana Dashboard Update**: A new panel titled 'Register Dispatcher StartTs Lag' has been added to the `ticdc_new_arch.json` Grafana dashboard, visualizing the p80, p95, and maximum percentiles of this new metric.
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style …
```
=> eventstore: add metric for dispatcher startTs lag at register

logservice/schemastore/schema_store.go, metrics/grafana/ticdc_new_arch.json, pkg/metrics/event_store.go, pkg/metrics/schema_store.go
Issue Number: close #1562 
* **New Metric for Schema Store Latency**: A new Prometheus histogram, `SchemaStoreWaitResolvedTsDurationHist`, has been introduced to measure the duration of the `waitResolvedTs` operation within the schema store.
- Unit test
- No code
```release-note
```
=> schemastore: add wait resolved ts metrics

pkg/etcd/etcdkey.go, server/module_election.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2493
This pull request implements a crucial change to support safe rollbacks from the new TiCDC architecture to the old one. It achieves this by introducing a distinct etcd key prefix for components belonging to the new architecture. Specifically, the logCoordinator's etcd key is now stored under this new prefix, preventing the older TiCDC architecture from encountering and potentially panicking over unfamiliar etcd keys during a rollback scenario. This ensures greater stability and compatibility between different architectural versions.
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style …
```
=> logCoordinator: use a new etcd key to avoid panic when rollback to old arch ticdc

logservice/eventstore/event_store.go, pkg/eventservice/event_broker.go
Issue Number: close #2492
- Unit test
- No code
```release-note
```
=> eventstore: avoid useless scan when dispatcher for empty tables initialize
