pingcap/ticdc

pkg/messaging/message_center.go, pkg/messaging/target.go, server/module_grpc.go
=> messgaing: fix reconnect remote target

logservice/eventsource/eventsource.go, pkg/common/table_span.go, pkg/common/txn_event.go, pkg/common/types.go, pkg/eventservice/event_service.go, pkg/messaging/message.go, pkg/messaging/message_center_integration_test.go, utils/threadpool/task_scheduler_instance.go
=> eventservice: implement event service framework

pkg/eventservice/event_broker.go, pkg/eventservice/event_service_test.go
=> eventService:  adjust some code to make it works well with eventStore

downstreamadapter/eventcollector/event_collector.go, maintainer/maintainer.go, pkg/eventservice/event_broker.go, pkg/messaging/message_center.go, server/watcher/module_node_manager.go
=> *:  use TableIDToComparableSpan to get table's startKey 

pkg/messaging/message.go, server/metrics.go, server/metrics_server.go
=> server: add basic metrics

pkg/messaging/message_center.go, pkg/messaging/target.go, pkg/metrics/init.go, pkg/metrics/messaging.go, pkg/metrics/server.go, server/metrics.go
=> messaging: add some metrics

pkg/eventservice/event_broker.go, pkg/eventservice/event_broker_test.go, pkg/eventservice/event_service.go
This reverts commit c3f3b943506a58e4c6ca03a9bd55fbd32b1be0da.
=> Revert "eventService: refine eventService (#158)"

coordinator/changefeed.go, coordinator/coordinator.go, coordinator/coordinator_test.go, downstreamadapter/dispatchermanager/heartbeat_collector.go, downstreamadapter/dispathermanagermanager/dispatcher_manager_manager.go, downstreamadapter/eventcollector/event_collector.go, maintainer/fake_dispatcher_manager.go, maintainer/maintainer.go, maintainer/maintainer_manager.go, maintainer/replica_set.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_broker_test.go, pkg/eventservice/event_service.go, pkg/messaging/message.go, pkg/messaging/message_center.go, pkg/messaging/message_center_integration_test.go, pkg/messaging/target.go
=> eventBroker: batch send resolvedTs

downstreamadapter/writer/helper.go, downstreamadapter/writer/mysql_writer_test.go, downstreamadapter/writer/sql_builder.go, downstreamadapter/writer/sql_builder_test.go, pkg/common/helper.go, pkg/common/table_info.go, pkg/mounter/mounter_test.go, pkg/mounter/util.go
=> writer: add unit test for sql builder

logservice/eventstore/eventstore.go, logservice/logpuller/region_change_event_processor.go, pkg/common/column_selector_test.go, pkg/common/kv_entry.go, pkg/common/kv_entry_benchmark_test.go, pkg/common/kv_entry_test.go, pkg/eventservice/event_broker.go, pkg/mounter/mounter.go
<p>This PR reduces the cost of encoding and decoding RawKV and improves throughput.</p>
Row size | Master | This PR
-- | -- | --
4KB | 40MB/s | 110+ MB/s, lag 2-5s, CPU 400%
100KB | 40MB/s | 266 MB/s, lag 2-5s, CPU 550%
Note that the results in the rightmost column do not represent the program's performance limit, but are constrained by the amount of traffic we can write upstream.
=> evenStore: Optimize rawKV encoding and decoding, compressing

logservice/eventstore/eventstore.go, logservice/logpuller/log_puller.go, logservice/logpuller/log_puller_multi_span.go, logservice/schemastore/ddl_job_fetcher.go, logservice/schemastore/multiversion.go, logservice/schemastore/multiversion_test.go, logservice/schemastore/persist.go, logservice/schemastore/persist_test.go, logservice/schemastore/schemastore.go, logservice/schemastore/schemastore_test.go, maintainer/maintainer.go, maintainer/maintainer_manager_test.go, server/server.go, server/server_prepare.go, server/watcher/module_node_manager.go
* handle error
* adjust log level, make logs more detail
=> refactor log service

logservice/eventstore/eventstore.go, logservice/logpuller/log_puller.go, logservice/logpuller/log_puller_multi_span.go, logservice/schemastore/ddl_job_fetcher.go, logservice/schemastore/multiversion.go, logservice/schemastore/multiversion_test.go, logservice/schemastore/persist.go, logservice/schemastore/persist_test.go, logservice/schemastore/schemastore.go, logservice/schemastore/schemastore_test.go, maintainer/maintainer_manager_test.go, server/server.go, server/server_prepare.go, server/watcher/module_node_manager.go
This reverts commit e44d465b30e2b14c61f941929c6c3ce5b8c1c252.
=> Revert "refactor log service (#292)"

coordinator/coordinator.go, coordinator/coordinator_test.go, coordinator/scheduler.go, coordinator/supervisor.go, downstreamadapter/eventcollector/event_collector.go, maintainer/maintainer_manager.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_service.go, scheduler/component.go, server/server_prepare.go
fix some typo, adjust some code
=> Tiny adjust

go.mod, logservice/eventstore/event_store.go, pkg/eventservice/event_broker.go, pkg/metrics/event_store.go
=> eventService: remove pending queue

logservice/schemastore/disk_format.go, logservice/schemastore/persist_storage.go, logservice/schemastore/persist_storage_test.go, utils/dynstream/dynamic_stream.go
* user time.ticker instead of the after, to reduce the call of new timer.
* use switch instead of the else if, more easier to read
* fix several typos, remove redundant log prefix
=> refactor the dynamic stream.

downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/sink/mysql_sink_test.go, go.mod
Remove stale `github.com/flowbehappy/tigate/downstreamadapter/writer` imports.
=> downstreamadapter: remove stale `github.com/flowbehappy/tigate/downstreamadapter/writer` imports

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_handle_event_test.go, downstreamadapter/dispatcher/helper.go, downstreamadapter/downstream_performance_test.go, downstreamadapter/eventcollector/event_collector.go, downstreamadapter/sink/types/table_progress.go, pkg/common/event/dml_event.go, pkg/common/event/mounter.go, pkg/eventservice/event_broker.go, utils/dynstream/event_queue.go, utils/dynstream/interfaces.go, utils/dynstream/memory_control.go, utils/dynstream/memory_control_test.go
=> *: enable flow control

api/v2/api.go, api/v2/info.go, coordinator/controller.go, logservice/schemastore/multi_version.go, logservice/schemastore/persist_storage.go, pkg/eventservice/event_broker.go, pkg/sink/mysql/mysql_writer.go, tests/integration_tests/charset_gbk/data/test.sql, utils/threadpool/task.go, utils/threadpool/thread_pool.go
=> minor fix for controller, schemastore, eventbroker and thread pool 

downstreamadapter/dispatchermanager/event_dispatcher_manager.go, pkg/apperror/util.go
=> Fix create table trigger event dispatcher panic when the downstream is mysql

downstreamadapter/dispatcher/helper.go
=> dispatcher: add log for droped event

utils/dynstream/dynamic_stream_test.go, utils/dynstream/event_queue.go, utils/dynstream/event_queue_test.go
Signed-off-by: dongmen <414110582@qq.com>Signed-off-by: dongmen <414110582@qq.com>
=> ds: fix a bug that may cause event lost

maintainer/maintainer.go, metrics/grafana/ticdc.json, pkg/eventservice/event_broker.go, pkg/eventservice/helper.go, pkg/metrics/event_service.go
=> eventService: reduce resolvedTs lag

pkg/common/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/sql_builder.go
=> mysql: reduce build sql memory allocation

logservice/eventstore/event_store.go, pkg/eventservice/event_broker.go, pkg/metrics/event_store.go
=> eventService: reduce notify

pkg/eventservice/event_broker.go
=> eventBroker: handle resolvedTs in eventBroker

logservice/schemastore/disk_format.go, logservice/schemastore/persist_storage.go, pkg/common/event/resolved_ts_event.go, pkg/eventservice/dispatcher_stat.go, pkg/eventservice/event_broker.go
=> eventService: reduce notify number

downstreamadapter/dispatcher/helper.go, downstreamadapter/eventcollector/event_collector.go, downstreamadapter/eventcollector/helper.go, utils/dynstream/interfaces.go
=> DS: use buffer in eventCollector DS

logservice/eventstore/event_store.go
=> eventStore: adjust pebble setting

downstreamadapter/dispatchermanager/helper.go, downstreamadapter/eventcollector/helper.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_service.go, pkg/eventservice/helper.go
=> evenStore, eventService: enable store GC and other optimization

pkg/eventservice/dispatcher_stat.go, pkg/eventservice/event_broker.go
=> eventBroker: fix panic

downstreamadapter/eventcollector/event_collector.go, pkg/config/server.go, pkg/eventservice/event_broker.go, pkg/messaging/message.go
=> eventCollertor: handle event concurrently

utils/dynstream/dynamic_stream.go
=> DS: fix panic

coordinator/coordinator.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, maintainer/maintainer_manager.go
Signed-off-by: dongmen <414110582@qq.com>Signed-off-by: dongmen <414110582@qq.com>Signed-off-by: dongmen <414110582@qq.com>
=> metrics: add DS metrics for maintainer and coordinator

maintainer/maintainer.go, maintainer/maintainer_manager.go
=> maintainer: use goroutine to drive  

server/module_election.go
=> server: fix resign owner API 

.github/workflows/integration_test_mysql.yaml
Upload logs when ci fails to help debuging.
=> tests: upload ci logs

pkg/common/event/chunk.go, pkg/common/event/codec.go, pkg/common/helper.go, pkg/sink/codec/avro/arvo.go, pkg/sink/codec/canal/helper.go, pkg/sink/codec/common/verify_checksum.go, pkg/sink/codec/craft/message_decoder.go, pkg/sink/codec/craft/message_encoder.go, pkg/sink/codec/debezium/codec.go, pkg/sink/codec/internal/column.go, pkg/sink/codec/internal/java.go, pkg/sink/codec/open/codec.go, pkg/sink/codec/simple/message.go, pkg/sink/mysql/config.go, pkg/sink/mysql/format_ddl.go, pkg/sink/mysql/mysql_writer.go
ref https://github.com/pingcap/tiflow/issues/11530
=> *: support vector data type

.github/workflows/integration_test_mysql.yaml, tests/integration_tests/fail_over/run.sh, tests/integration_tests/fail_over_ddl_A/run.sh, tests/integration_tests/fail_over_ddl_B/run.sh, tests/integration_tests/fail_over_ddl_C/run.sh, tests/integration_tests/fail_over_ddl_D/run.sh, tests/integration_tests/fail_over_ddl_E/run.sh, tests/integration_tests/fail_over_ddl_F/run.sh
ref #757 
We will enable it again when it's fixed.
=> ci: disable integration test`changefeed_pause_resume`

downstreamadapter/worker/kafka_dml_worker.go, downstreamadapter/worker/mysql_worker.go, logservice/eventstore/event_store.go, pkg/metrics/statistics.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_test.go
=> statistics: add some comment and record executed dml count for the kafka sink

logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/persist_storage_test_utils.go
ref https://github.com/pingcap/ticdc/pull/752
=> schemastore: add multi schema change DDL

.github/actions/upload-test-logs/action.yml, .github/workflows/integration_test_mysql.yaml
=> test: fix_upload_ci_log3

.github/pull_request_template.md, .github/workflows/check_and_build.yaml, .github/workflows/integration_test_mysql.yaml, .github/workflows/uint_test.yaml, CONTRIBUTING.md, pkg/common/event/chunk.go, pkg/common/table_info.go, pkg/common/table_info_helper.go, pkg/common/table_info_helper_test.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/sql_builder.go, tests/integration_tests/generate_column/data/virtual.sql, utils/dynstream/parallel_dynamic_stream.go
=> test: fix `generate_column` integration test  case

.github/workflows/integration_test_mysql.yaml, tests/integration_tests/_utils/check_logs
Issue Number: ref #442 
This PR add the following cases:
1. many_pk_or_uk
2. drop_many_tables
3. new_ci_collation
4. region_merge
```release-note
None
```
=> tests: add more integration test cases

logservice/logpuller/region_event_handler.go, tests/integration_tests/multi_tables_ddl/run.sh
- Unit test
- No code
```release-note
```
=> tests: fix multi_tables_ddl test

tests/integration_tests/_utils/check_changefeed_status, tests/integration_tests/capture_suicide_while_balance_table/run.sh, tests/integration_tests/changefeed_error/run.sh, tests/integration_tests/changefeed_reconstruct/run.sh, tests/integration_tests/cli_tls_with_auth/run.sh, tests/integration_tests/cli_with_auth/run.sh, tests/integration_tests/fail_over_ddl_E/run.sh, tests/integration_tests/kill_owner_with_ddl/run.sh, tests/integration_tests/synced_status/run.sh, tests/integration_tests/synced_status_with_redo/run.sh
filter some text to avoid jq parsing failed
=> test: update some test

api/middleware/middleware.go, api/middleware/middleware_test.go
Issue Number: close #814 
- Unit test
```release-note
None
```
=> api: fix api request never return

logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/persist_storage_test_utils.go, pkg/common/event/ddl_event.go, tests/integration_tests/multi_tables_ddl_v2/run.sh
Issue Number: close #800 
- Unit test
- No code
```release-note
```
=> schemastore: support alter/remove partition

logservice/logpuller/region_request_worker.go
Issue Number: close #794 
- Unit test
- No code
```release-note
```
=> test: fix default test

pkg/scheduler/replica/replication.go
Issue Number: close #https://github.com/pingcap/ticdc/issues/776
- Unit test
- No code
```release-note
```
=> Fix bug in schedule group

downstreamadapter/dispatcher/helper.go, downstreamadapter/dispatchermanager/helper.go
Issue Number: close #https://github.com/pingcap/ticdc/issues/838
=> Fix data race when use sync.Once

utils/dynstream/event_queue.go, utils/dynstream/event_queue_test.go, utils/dynstream/parallel_dynamic_stream.go, utils/dynstream/stream.go
Issue Number: close https://github.com/pingcap/ticdc/issues/830
- Unit test
- No code
```release-note
```
=> fix data race in ds

logservice/schemastore/multi_version.go, pkg/eventservice/event_broker.go
Issue Number: close #810 
- Unit test
- No code
```release-note
```
=> logservice: ignore deleted table

.github/workflows/integration_test_mysql.yaml
Issue Number: ref #442 
Add integration test case `http_proxies` to CI.
```release-note
None
```
=> ci: add test case `http_proxies`

pkg/sink/codec/canal/codec_test.go, pkg/sink/codec/canal/encoder.go, pkg/sink/codec/canal/helper.go, pkg/sink/codec/common/message.go, pkg/sink/codec/open/codec.go, pkg/sink/codec/open/codec_test.go, pkg/sink/codec/open/encoder.go, pkg/sink/codec/open/encoder_test.go
- Unit test
- No code
```release-note
```
=> codec: refactor open-protocol

pkg/eventservice/event_broker.go
=> eventservice: fix truncate table

downstreamadapter/worker/kafka_dml_worker.go, tests/integration_tests/canal_json_adapter_compatibility/run.sh, tests/integration_tests/canal_json_basic/run.sh, tests/integration_tests/canal_json_content_compatible/run.sh, tests/integration_tests/canal_json_handle_key_only/run.sh, tests/integration_tests/kafka_big_messages/run.sh, tests/integration_tests/kafka_big_messages_v2/run.sh, tests/integration_tests/kafka_column_selector/run.sh, tests/integration_tests/kafka_compression/run.sh, tests/utils/checksum_checker/main.go, tests/utils/gen_kafka_big_messages/main.go, tests/utils/gen_kafka_big_messages/main_test.go
close https://github.com/pingcap/ticdc/issues/872
=> test: fix kafka test

downstreamadapter/sink/mysql_sink.go, downstreamadapter/sink/sink.go, pkg/messaging/target.go
Issue Number: close #876
```release-note
None
```
=> messaging: fix data race

downstreamadapter/worker/kafka_ddl_worker_test.go, downstreamadapter/worker/kafka_dml_worker_test.go, downstreamadapter/worker/producer/kafka_ddl_producer_test.go, downstreamadapter/worker/producer/kafka_dml_producer_test.go, pkg/sink/codec/open/codec_test.go, pkg/sink/codec/open/encoder_test.go
- Unit test
- No code
```release-note
```
=> kafka: fix broken dml and ddl producer unit test

downstreamadapter/downstream_performance_test.go, pkg/common/event/ddl_event.go, pkg/common/event/row_change.go, pkg/config/changefeed.go, pkg/filter/filter.go, pkg/sink/codec/encoder_group.go, pkg/sink/codec/open/codec_test.go
As title.
- No code
```release-note
None
```
=> *: remove all Chinese comments

metrics/grafana/ticdc_new_arch.json
- Unit test
- No code
```release-note
```
=> metrics: update lag summary panel

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/dispatchermanager/helper.go, downstreamadapter/sink/helper/eventrouter/partition/generator.go, downstreamadapter/sink/kafka_sink.go, downstreamadapter/sink/mysql_sink.go, downstreamadapter/worker/mysql_worker.go, pkg/common/event/dml_event.go, pkg/common/event/util.go, pkg/sink/mysql/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_test.go
- Unit test
- No code
```release-note
```
=> dispatcher: refactor mysql sink and dispatcher

cmd/cdc/server/server.go, coordinator/changefeed/changefeed.go, coordinator/changefeed/changefeed_test.go, coordinator/controller.go, server/server.go, tests/integration_tests/http_api_tls/run.sh, tests/integration_tests/http_api_tls_with_user_auth/run.sh
Issue Number: close #894 
Use a cloned status when modifications are needed.
- Unit test
```release-note
None
```
=> changefeed: fix data race

.github/workflows/integration_test_mysql.yaml, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/sql_builder.go, pkg/sink/mysql/sql_builder_benchmark_test.go, pkg/sink/mysql/sql_builder_test.go, tests/integration_tests/tidb_mysql_test/run.sh
=> sink: support force replicate

logservice/schemastore/persist_storage_ddl_handlers.go, tests/integration_tests/batch_add_table/run.sh
- Unit test
- No code
```release-note
```
=> schemastore: fix table filter

downstreamadapter/sink/helper/eventrouter/partition/generator.go, metrics/grafana/ticdc_new_arch.json
Issue Number: close #919 
- Unit test
- No code
```release-note
`None`
```
=> monitor: set the y min to 0 for panels

.github/workflows/integration_test_mysql.yaml, .github/workflows/uint_test.yaml, downstreamadapter/sink/kafka_sink_test.go, downstreamadapter/sink/mysql_sink_test.go, logservice/coordinator/coordinator_test.go, maintainer/maintainer.go, maintainer/maintainer_test.go
Issue Number: ref https://github.com/pingcap/ticdc/issues/920
- Unit test
- No code
```release-note
```
=> Fix data race in ut

logservice/schemastore/persist_storage_ddl_handlers.go
Issue Number: close #920 
- Unit test
- No code
```release-note
```
=> schemastore: fix unit test

logservice/logpuller/subscription_client_test.go
- Unit test
- No code
```release-note
```
=> test: try fix unstable test

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/sink/helper/eventrouter/partition/generator.go, maintainer/barrier_event.go, pkg/common/event/dml_event.go, tests/integration_tests/availability/capture.sh, tests/integration_tests/capture_suicide_while_balance_table/run.sh, tests/integration_tests/cli_tls_with_auth/run.sh
This PR enables lint checks in the CI pipeline to enforce coding standards and improve code quality. Existing issues in the codebase have been fixed to ensure the CI pipeline passes successfully with these checks enabled.  
- Unit test
```release-note
None
```
=> ci: enable lint checks in CI and fix related code issues

logservice/schemastore/persist_storage_ddl_handlers.go
- Unit test
- No code
```release-note
```
=> schemastore: support schema charset

.github/workflows/integration_test_mysql.yaml
- Unit test
- No code
```release-note
```
=> Enable integration test `cdc`

.github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/ISSUE_TEMPLATE/ticdc-bug-report.yml
Issue Number: close #941 
Add github issue template.
- No code
```release-note
None
```
=> github: add issue template

logservice/schemastore/disk_format.go, logservice/schemastore/persist_storage_test.go, logservice/schemastore/persist_storage_test_utils.go, tests/integration_tests/mysql_sink_retry/run.sh
- Unit test
- No code
```release-note
```
=> test: fix schemastore unit tests

logservice/schemastore/multi_version.go, logservice/schemastore/multi_version_test.go
- Unit test
- No code
```release-note
```
=> *: fix schema store log

coordinator/controller.go
Issue Number: close https://github.com/pingcap/ticdc/issues/956
- Unit test
- No code
```release-note
```
=> Fix data race in coordinator

.github/workflows/integration_test_mysql.yaml, downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/eventcollector/event_collector.go, downstreamadapter/sink/mysql_sink.go, downstreamadapter/sink/mysql_sink_test.go, downstreamadapter/syncpoint/sync_point.go, downstreamadapter/worker/mysql_worker.go, maintainer/barrier.go, maintainer/barrier_event.go, maintainer/barrier_event_test.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go, pkg/sink/mysql/mysql_writer_test.go, tests/integration_tests/fail_over_ddl_mix/run.sh, tests/integration_tests/fail_over_ddl_mix_with_syncpoint/conf/changefeed.toml, tests/integration_tests/fail_over_ddl_mix_with_syncpoint/conf/diff_config.toml, tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh
- Unit test
- No code
```release-note
```
=> Fix the corner case with ddl and syncpoint share the same commit; Add a new test for random ddl failover test 

server/server_prepare.go
- Unit test
- No code
```release-note
```
=> *: fix panic when server prepare

logservice/logpuller/subscription_client.go
After unsubscribe a subscription, there may still be more region events to handle(like region error). So we should remove path in `onTableDrained` instead.
- Unit test
- No code
```release-note
```
=> puller: fix remove path

logservice/schemastore/persist_storage_ddl_handlers.go, pkg/common/event/ddl_event.go
- Unit test
- No code
```release-note
```
=> ddl: add multiple table infos

coordinator/changefeed/backoff.go, coordinator/changefeed/changefeed.go, coordinator/changefeed/changefeed_db.go, coordinator/changefeed/changefeed_db_test.go, coordinator/controller.go, coordinator/coordinator.go, coordinator/operator/operator_controller.go, coordinator/operator/operator_stop.go, downstreamadapter/dispatcher/dispatcher.go, logservice/eventstore/event_store.go, maintainer/maintainer.go, maintainer/maintainer_manager.go, maintainer/operator/operator_controller.go, pkg/common/format.go, pkg/eventservice/event_broker.go, pkg/node/node.go, server/module_election.go, tests/integration_tests/changefeed_dup_error_restart/run.sh
Issue Number: close #963 
1. Standardize the log format within coordinator package.
2. Streamline the `handleMaintainerStatus` method in coordinator/controller.go.
3. Increase retry times of `check_sync_diff` in the test case `changefeed_dup_error_restart`.
- No code
```release-note
None
```
=> coordinator: improve the log format and code struct

api/v2/api.go, api/v2/changefeed.go, api/v2/model.go, api/v2/processor.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/dispatchermanager/helper.go, maintainer/maintainer.go, pkg/config/changefeed.go, pkg/eventservice/event_service.go, pkg/messaging/message.go, tests/integration_tests/availability/capture.sh, tests/integration_tests/availability/owner.sh, tests/integration_tests/cli_tls_with_auth/run.sh, tests/integration_tests/cli_with_auth/run.sh, tests/integration_tests/http_api/run.sh
Issue Number: ref #989 
```release-note
None
```
=> api: make all api/v2 compatible with old TiCDC. 

downstreamadapter/sink/mysql_sink_test.go, pkg/common/table_info.go, pkg/common/table_info_helper.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/sql_builder.go, pkg/sink/sqlmodel/multi_row.go, pkg/sink/sqlmodel/row_change.go, pkg/sink/sqlmodel/utils.go, pkg/sink/sqlmodel/where_handle.go, tests/integration_tests/cdc/cdc.go, tests/integration_tests/cdc/dailytest/case.go
- Unit test
- No code
```release-note
```
=> Support batch dml in mysql sink

logservice/logpuller/region_event_handler.go, logservice/logpuller/region_request_worker.go
- Unit test
- No code
```release-note
```
=> puller: small refactor

logservice/schemastore/multi_version.go, logservice/schemastore/multi_version_test.go, logservice/schemastore/multi_version_test_utils.go, logservice/schemastore/persist_storage.go
Issue Number: close #985 
- Unit test
- No code
```release-note
```
=> schemastore: fix panic after recover table

.github/workflows/integration_test_mysql.yaml, logservice/schemastore/disk_format.go, logservice/schemastore/persist_storage_ddl_handlers.go
- Unit test
- No code
```release-note
```
=> schemastore: fix load full table info failed

downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/eventcollector/event_collector.go, metrics/grafana/ticdc_new_arch.json, pkg/common/types.go, pkg/eventservice/event_broker.go, pkg/metrics/ds.go, pkg/sink/mysql/config.go, pkg/sink/mysql/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_ddl.go, tests/integration_tests/ds_memory_control/conf/diff_config.toml, tests/integration_tests/ds_memory_control/conf/workload, tests/integration_tests/ds_memory_control/conf/workload-2, tests/integration_tests/ds_memory_control/run.sh, utils/dynstream/interfaces.go, utils/dynstream/memory_control.go, utils/dynstream/memory_control_test.go, utils/dynstream/parallel_dynamic_stream.go, utils/dynstream/stream.go, utils/dynstream/stream_test.go
Issue Number: ref #994 
1. Add config for mysql sink dry run mode. 
2. Refactor memory control and add some log to help debugging.
3. Add changefeed lable to sink memory control metric.
- Unit test
```release-note
None
```
=> DS, mysql: enhance dry run mode and refactor DS memory control 

logservice/schemastore/schema_store.go
- Unit test
- No code
```release-note
```
=> schemastore: ignore system schema

pkg/sink/mysql/mysql_writer_dml.go
- Unit test
- No code
```release-note
```
=> Add log for debug

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/sink/blackhole.go, downstreamadapter/sink/cloudstorage.go, downstreamadapter/sink/conflictdetector/conflict_detector.go, downstreamadapter/sink/conflictdetector/helper.go, downstreamadapter/sink/conflictdetector/node.go, downstreamadapter/sink/conflictdetector/slot.go, downstreamadapter/sink/conflictdetector/txn_cache.go, downstreamadapter/sink/kafka_sink.go, downstreamadapter/sink/mysql_sink.go, downstreamadapter/sink/sink.go, downstreamadapter/worker/mysql_worker.go, pkg/common/event/dml_event.go, pkg/common/table_info.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1013
```release-note
None
```
=> mysql-sink: support conflict detector for mysql sink

downstreamadapter/sink/mysql_sink.go, downstreamadapter/sink/sink.go, pkg/sink/mysql/config.go
- Unit test
- No code
```release-note
```
=> Fix the worker-count of mysql sink

api/v2/model.go, downstreamadapter/eventcollector/helper.go, maintainer/maintainer_controller.go, maintainer/maintainer_controller_test.go, maintainer/replica/checker.go, maintainer/replica/checker_test.go, maintainer/scheduler.go, maintainer/split/region_count_splitter.go, maintainer/split/region_count_splitter_test.go, maintainer/split/splitter.go, maintainer/split/write_bytes_splitter.go, maintainer/split/write_bytes_splitter_test.go, pkg/config/replica_config.go, pkg/config/scheduler_config.go
1. disable check imbalance to make split more stable
2. frequently check hot spans to make split more timely
- Unit test
- No code
```release-note
```
=> Add some logs and adjust the param for split table

logservice/logpuller/errors.go, logservice/logpuller/region_request_worker.go, logservice/logpuller/subscription_client.go, server/server.go, tools/workload/main.go
1. add `requestCancelledErr` to avoid retry region after unsubscribe;
2. avoid some unnecessary log;
3. ignore resolved ts 0 event;
- Unit test
- No code
```release-note
```
=> puller: small improvement

tests/integration_tests/run_heavy_it_in_ci.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1037
Added export TICDC_NEWARCH=true to the CI test script.
```release-note
None
```
=> ci: fix ci by enable TICDC_NEWARCH for new arch

maintainer/maintainer_controller_test.go, maintainer/replica/checker.go, pkg/pdutil/clock.go
- Unit test
- No code
```release-note
```
=> Don't merge spans when the checkpoint lag is large

downstreamadapter/dispatchermanager/event_dispatcher_manager.go, maintainer/barrier.go, maintainer/maintainer.go, maintainer/maintainer_controller.go, maintainer/operator/operator_controller.go
obtain lock when calculate checkpointTs to calculate it correctly
- Unit test
- No code
```release-note
```
=> Fix the wrong update of checkpointTs

tests/integration_tests/_utils/check_coverage.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1046
This PR introduces a CI check that ensures all test cases listed in groups are present in the integration_tests directory. This helps catch manual errors when adding test cases to groups, preventing typos or incorrect test names from going unnoticed.
No.
No.
```release-note
None
```
=> ci: add check to validate test cases in groups

pkg/common/event/ddl_event.go
- Unit test
- No code
```release-note
`None`.
```
=> sink: fix topic dispatchers for renaming tables 

logservice/schemastore/multi_version_test.go, logservice/schemastore/persist_storage_test.go
- Unit test
- No code
```release-note
```
=> schemastore: improve unit tests

go.mod, logservice/eventstore/event_store.go, logservice/eventstore/pebble.go, logservice/eventstore/pebble_test.go, logservice/logpuller/subscription_client.go
- Unit test
- No code
```release-note
```
=> eventstore: remove zstd and adjust pebble options

logservice/logpuller/region_event_handler.go
- Unit test
- No code
```release-note
```
=> puller: fix panic

logservice/logpuller/region_request_worker.go
Issue Number: close #1067
Add cdc version in deregister request header.
The reason why this is needed is described in the issue.
- Unit test
- No code
```release-note
```
=> puller: fix potential stuck

tests/integration_tests/multi_source/main.go
Issue Number: ref #1068 ref https://github.com/pingcap/tiflow/pull/12085
- Unit test
```release-note
`None`.
```
=> test: fix multi_source test

.github/workflows/integration_test_mysql.yaml, pkg/sink/mysql/mysql_writer_test.go, tests/integration_tests/changefeed_dup_error_restart/run.sh
- Unit test
- No code
```release-note
```
=> Fix unstable test changefeed_dup_error_restart

utils/dynstream/interfaces.go, utils/dynstream/stream.go
Fix some inaccurate docs of dynamic stream
Issue Number: close #1005
- Unit test
- No code
```release-note
None
```
=> Fix docs of ds

tests/integration_tests/run_heavy_it_in_ci.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1089
These changes aim to better distribute the tests between lightweight and heavyweight groups based on resource requirements, ensuring that integration testing is more efficient. The goal is to minimize waiting time for resources and reduce overall testing time by making the most of available CPU resources.
Time and resource usage were monitored after changes.
No.
No.
```release-note
None
```
=> ci: refactor mysql it groups to optimize resource allocation and cost of time

cmd/cdc/server/server.go, downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, pkg/common/event/dml_event.go, pkg/common/event/mounter.go, pkg/common/event/row_change.go, pkg/config/sink_protocol.go, pkg/eventservice/event_broker.go, pkg/sink/codec/common/config.go, pkg/sink/codec/common/message.go
Issue Number: close #1088
* remove unused code 
* use `"github.com/pingcap/ticdc/pkg/errors"` as the default error handling package
- Unit test
```release-note
`None`
```
=> *: remove some unused code and refactor

downstreamadapter/worker/cloudstorage_ddl_worker_test.go, downstreamadapter/worker/writer/defragmenter_test.go, downstreamadapter/worker/writer/worker_test.go, downstreamadapter/worker/writer/writer_test.go, logservice/schemastore/ddl_job_fetcher.go, logservice/schemastore/disk_format.go, logservice/schemastore/multi_version_test_utils.go, logservice/schemastore/persist_storage_ddl_handlers.go, pkg/common/event/ddl_event_test.go, pkg/common/event/redo_gen_compatibility_test.go, pkg/common/event/util.go, pkg/common/table_info.go, pkg/eventservice/event_service_test.go, pkg/sink/cloudstorage/path_test.go, pkg/sink/cloudstorage/table_definition.go, pkg/sink/cloudstorage/table_definition_test.go, pkg/sink/codec/csv/csv_message_test.go
Issue Number: close #1092
* remove the schemaID field from the table info structure
- Unit test
```release-note
`None`
```
=> tableInfo: remove the schema ID field from the table info since it's not used

metrics/grafana/ticdc_new_arch.json
- Unit test
- No code
```release-note
```
=> metrics: add changefeed to panel `Sink Write Bytes`

downstreamadapter/sink/helper/eventrouter/event_router.go, downstreamadapter/sink/helper/eventrouter/event_router_test.go, downstreamadapter/worker/mq_ddl_worker.go, downstreamadapter/worker/mq_dml_worker.go, pkg/common/event/chunk.go, pkg/common/event/dml_event.go, pkg/common/table_info.go, pkg/common/table_info_helper.go
Issue Number: close #1098
- Unit test
- No code
```release-note
`None`
```
=> kafka: refactor the generator

logservice/eventstore/event_store.go, metrics/grafana/ticdc_new_arch.json, pkg/metrics/event_store.go
Add metrics:
- Unit test
- No code
```release-note
```
=> eventstore: clean data after unsubscribe and add some metrics

pkg/sink/codec/canal/canal_json_encoder.go, pkg/sink/codec/canal/canal_json_message.go, pkg/sink/codec/canal/canal_json_txn_encoder.go, pkg/sink/codec/canal/helper.go, pkg/sink/codec/canal/java.go, pkg/sink/codec/common/helper.go, pkg/sink/codec/encoder_builder.go, pkg/sink/codec/open/encoder.go, pkg/sink/codec/open/message.go
Issue Number: close #1102
- Unit test
```release-note
`None`
```
=> codec: move some files to the corresponding folder and refactor canal-json encoder

logservice/eventstore/event_store.go, logservice/eventstore/pebble_test.go, logservice/schemastore/multi_version_test.go, logservice/schemastore/multi_version_test_utils.go, logservice/schemastore/persist_storage_ddl_handlers.go, logservice/schemastore/persist_storage_test.go
- Unit test
- No code
```release-note
```
=> schemastore: fix drop partition table

logservice/logpuller/subscription_client.go
Issue Number: close #1131
As in code comments.
```release-note
None
```
=> puller: fix dead lock

coordinator/changefeed/backoff.go, coordinator/controller.go, tests/integration_tests/_utils/do_retry, tests/integration_tests/multi_tables_ddl/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close #1127 
```release-note
None
```
=> tests: fix integration test `multi_tables_ddl`

logservice/schemastore/persist_storage.go
Issue Number: close #1152
- Unit test
```release-note
`None`.
```
=> schemastore: add retry when SetServiceGCSafepoint meet error

downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go, server/server.go, tests/integration_tests/_utils/run_cdc_cli, tests/integration_tests/fail_over/run.sh, tests/integration_tests/fail_over_ddl_A/run.sh, tests/integration_tests/fail_over_ddl_B/run.sh, tests/integration_tests/fail_over_ddl_C/run.sh, tests/integration_tests/fail_over_ddl_D/run.sh, tests/integration_tests/fail_over_ddl_E/run.sh, tests/integration_tests/fail_over_ddl_F/run.sh, tests/integration_tests/fail_over_ddl_G/run.sh, tests/integration_tests/fail_over_ddl_H/run.sh, tests/integration_tests/fail_over_ddl_I/run.sh, tests/integration_tests/fail_over_ddl_J/run.sh, tests/integration_tests/fail_over_ddl_K/run.sh, tests/integration_tests/fail_over_ddl_L/run.sh, tests/integration_tests/fail_over_ddl_M/run.sh, tests/integration_tests/fail_over_ddl_N/run.sh, tests/integration_tests/fail_over_ddl_O/run.sh, tests/integration_tests/fail_over_ddl_mix/run.sh, tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1160
- Unit test
- No code
```release-note
```
=> dispacther: fix a data race

logservice/schemastore/persist_storage_ddl_handlers.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1165
- Unit test
- No code
```release-note
```
=> Fix tidb-only setting for partition ddls

metrics/grafana/ticdc_new_arch.json, pkg/common/metrics.go, pkg/metrics/init.go
Issue Number: close #1145 
* fix the gc safe point not initialized
* adjust some monitoring, set short for some display
- Unit test
```release-note
`None`
```
=> metrics: fix gc safe point metrics and adjust some monitoring

tests/integration_tests/run_heavy_it_in_ci.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1167
**Description**:
This PR introduces CI workflows for Kafka, Pulsar, and Storage integration tests, ensuring they run consistently and efficiently.
**Changes**:
* Configured CI for Kafka, Pulsar, and Storage integration tests
* Ensured proper setup and teardown for test environments
* Optimized resource usage to prevent unnecessary delays in CI
* Verified test stability across multiple CI runs
With this CI setup, integration tests will be automatically executed, improving test coverage and reducing the risk of undetected issues.
No.
No.
```release-note
None
```
=> ci: add ci for kafka, pulsar and storage integration tests

pkg/messaging/remote_target.go
Issue Number: close #1224
- Unit test
```release-note
`None`.
```
=> messaging: fix a data race in message target

pkg/sink/codec/csv/csv_decoder.go, pkg/sink/codec/csv/csv_decoder_test.go, pkg/sink/codec/csv/csv_message.go
Issue Number: close #1231
- Unit test
```release-note
`None`.
```
=> codec: add csv protocol decoder 

pkg/errors/error.go, pkg/sink/codec/debezium/decode.go
Issue Number: close #1232
- Unit test
```release-note
`None`.
```
=> codec: add debezium protocol decoder 

downstreamadapter/sink/mysql/sink.go, maintainer/maintainer_controller.go, maintainer/split/region_count_splitter.go, maintainer/split/region_count_splitter_test.go, maintainer/split/splitter.go
- Unit test
- No code
```release-note
```
=> split: add unit test for region count splitter

OWNERS_ALIASES, pkg/config/OWNERS
The changes in `pkg/config` folder must be approved by owner SIG `sig-critical-approvers`
Issue Number: ref #537
- Unit test
- No code
```release-note
None
```
=> CI: add OWNERS files with sig-critical-approvers aliases

downstreamadapter/sink/kafka/sink.go, downstreamadapter/sink/pulsar/sink.go, pkg/common/event/dml_event.go, pkg/sink/codec/avro/decoder.go, pkg/sink/codec/canal/canal_json_decoder.go, pkg/sink/codec/canal/canal_json_txn_decoder.go, pkg/sink/codec/common/helper.go, pkg/sink/codec/common/utils.go, pkg/sink/codec/common/verify_checksum.go, pkg/sink/codec/csv/csv_decoder.go, pkg/sink/codec/debezium/decode.go, pkg/sink/codec/open/decoder.go, pkg/sink/codec/simple/decoder.go
Issue Number: ref #1244
- Unit test
```release-note
`None`.
```
=> *: fix incorrect row checksum

Makefile, cmd/cdc/main.go, cmd/cdc/redo/apply.go, cmd/cdc/redo/apply_test.go, cmd/cdc/redo/meta.go, cmd/cdc/redo/redo.go, go.mod, pkg/applier/main_test.go, pkg/applier/redo.go, pkg/applier/redo_test.go, pkg/errors/error.go, pkg/fsutil/preallocate_linux.go, pkg/util/memory.go
Issue Number: ref #1061
- Unit test
```release-note
`None`.
```
=> redo: add redo cmd

api/v2/capture.go, api/v2/model.go, cmd/cdc/cli/cli_capture_list.go, tests/integration_tests/cli_tls_with_auth/run.sh, tests/integration_tests/cli_with_auth/run.sh
Issue Number: close #1282 
* keep the http server return the same as the old architecture 
* client rewrite the `_` into `-`, the same as the old architecture
- Unit test
```release-note
`None`
```
=> api: fix the client return no owner

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/helper.go, pkg/config/debug.go, pkg/eventservice/dispatcher_stat.go, pkg/eventservice/dispatcher_stat_test.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_broker_test.go, utils/dynstream/stream.go
Issue Number: ref #1124
```release-note
```
=> eventService: fix a bug that may cause event seq error

maintainer/replica/checker.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1141
hotspan will be replaced later, now we first workaround the panic first
- Unit test
- No code
```release-note
```
=> workaround panic in maintainer

go.mod, go.sum
- Unit test
- No code
```release-note
```
=> update tiflow dependency

tests/integration_tests/ddl_with_random_move_table/conf/diff_config.toml, tests/integration_tests/ddl_with_random_move_table/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
- Unit test
- No code
```release-note
```
=> test: Add intergration test for random ddl with random table scheduling

downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go
Issue Number: ref https://github.com/pingcap/ticdc/issues/1306
- Unit test
- No code
```release-note
```
=> log: add some log in remove dispatcher

api/v2/changefeed.go, changefeed.toml, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/sink/eventrouter/event_router.go, downstreamadapter/sink/eventrouter/partition/generator.go, downstreamadapter/sink/eventrouter/partition/index_value.go, downstreamadapter/sink/eventrouter/topic/topic.go, downstreamadapter/sink/mysql/causality/conflict_detector.go, downstreamadapter/sink/mysql/causality/txn_cache.go, downstreamadapter/sink/mysql/sink.go, downstreamadapter/sink/mysql/sink_test.go, downstreamadapter/sink/sink.go, pkg/common/table_info.go, pkg/common/table_info_helper.go, pkg/sink/mysql/config.go, pkg/sink/mysql/config_test.go, pkg/sink/mysql/helper.go, pkg/sink/mysql/mysql_writer.go, pkg/sink/mysql/mysql_writer_ddl.go, pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_helper.go, pkg/sink/mysql/mysql_writer_test.go
Issue Number: close #1314 
* Change in row type checking logic in DML generation.
* Renaming of configuration and sink construction functions.
* Adjustments to logging and error handling in multiple packages.
- Unit test
```release-note
`None`
```
=> kafka, mysql: refactor the interface and some tiny adjust

pkg/sink/codec/avro/confluent_schema_registry.go, pkg/sink/codec/avro/decoder.go, pkg/sink/codec/avro/encoder_test.go, pkg/sink/codec/builder.go, pkg/sink/codec/canal/canal_json_decoder.go, pkg/sink/codec/canal/canal_json_test.go, pkg/sink/codec/canal/canal_json_txn_decoder.go, pkg/sink/codec/common/config.go, pkg/sink/codec/common/ddl.go, pkg/sink/codec/common/ddl_test.go, pkg/sink/codec/common/decoder.go, pkg/sink/codec/common/helper.go, pkg/sink/codec/common/table_info_cache.go, pkg/sink/codec/common/verify_checksum.go, pkg/sink/codec/csv/csv_decoder.go, pkg/sink/codec/csv/csv_decoder_test.go, pkg/sink/codec/debezium/decode.go, pkg/sink/codec/open/decoder.go, pkg/sink/codec/open/encoder_test.go, pkg/sink/codec/open/message.go, pkg/sink/codec/simple/decoder.go, pkg/sink/codec/simple/encoder_test.go
Issue Number: close #1317 
* remove error from the decoder interface, just panic immediately if meet error.
- Unit test
```release-note
`None`
```
=> codoc: decoder no need to report error to simplify the caller logic

pkg/common/event/util.go
Issue Number: ref #1325 
Add a DML2UpdateEvent method to assist with testing.
- Unit test
```release-note
None
```
=> event: add a DML2UpdateEvent method to assist with testing

pkg/txnutil/gc/gc_manager.go
Issue Number: close #1311
There are two functions called `TryUpdateGCSafePoint`, but only one in the old arch.
- Unit test
```release-note
`None`.
```
=> txnutil: fix data race in gcManager

maintainer/operator/operator_move.go, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1321
- Unit test
- No code
```release-note
```
=> Avoid move table from the node to the same node

pkg/sink/mysql/mysql_writer_dml.go, pkg/sink/mysql/mysql_writer_dml_test.go
Issue Number: close #1325 
- Unit test
```release-note
None
```
=> mysql: fix duplicate key error

tools/workload/app.go, tools/workload/schema/crawler/crawler.go, tools/workload/update.go
- Unit test
- No code
```release-note
```
=> tools: fix crawler workload

pkg/sink/codec/debezium/decoder.go, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #1087
- Unit test
```release-note
`None`.
```
=> codec: fix debezium decoder

metrics/grafana/ticdc_new_arch.json
Issue Number: close #1334 
1. Move Memory Quota panel to Summary row.
2. Add Eventservice dispatcher status panel.
3. Fix the issue where some monitoring panels cannot be displayed properly in clusters deployed by TiDB operator. 
- No code
```release-note
None
```
=> metric: improve dashboard

metrics/grafana/ticdc_new_arch.json
- Unit test
- No code
```release-note
```
=> metrics: fix typo

downstreamadapter/dispatcher/dispatcher_test.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/sink/blackhole/sink.go, downstreamadapter/sink/cloudstorage/sink.go, downstreamadapter/sink/kafka/sink.go, downstreamadapter/sink/mysql/sink.go, downstreamadapter/sink/mysql/sink_test.go, downstreamadapter/sink/pulsar/sink.go, downstreamadapter/sink/sink.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go
- Unit test
- No code
```release-note
```
=> dispatcher: remove GetStartTsList from sink interface, instead be a special function of mysql sink

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatcher/dispatcher_block_event.go, downstreamadapter/dispatcher/dispatcher_info.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/dispatchermanager/helper.go, downstreamadapter/eventcollector/event_collector.go
- Unit test
- No code
```release-note
```
=> dispatcher: reorg the functions in dispatcher to make code clean

logservice/logpuller/mock_upstream.go, logservice/logpuller/region_request_worker.go, logservice/logpuller/subscription_client.go, pkg/version/check.go
Issue Number: close #1348
- Unit test
```release-note
`None`
```
=> logpuller: fix the kv client query store id failed caused resolved-ts lag increase

downstreamadapter/dispatcher/dispatcher.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go, downstreamadapter/dispatchermanager/event_dispatcher_manager_info.go
- Unit test
- No code
```release-note
```
=> eventDispatcherManager: reorg the event dispatcher dispatcher to make code clean

api/v2/changefeed.go, downstreamadapter/sink/kafka/helper.go, pkg/sink/kafka/admin.go, pkg/sink/kafka/cluster_admin_client.go, pkg/sink/kafka/factory.go, pkg/sink/kafka/metrics_collector.go, pkg/sink/kafka/mock_cluster_admin_client.go, pkg/sink/kafka/mock_factory.go, pkg/sink/kafka/oauth2_token_provider.go, pkg/sink/kafka/options.go, pkg/sink/kafka/sarama.go, pkg/sink/kafka/sarama_factory.go
Issue Number: close #1360 
- Unit test
- No code
```release-note
`None`
```
=> kafka: option should be adjust first and then new the kafka factory

metrics/grafana/ticdc_new_arch.json
- Unit test
- No code
```release-note
```
=> metrics: change name to keep consistency with other component

pkg/sink/mysql/mysql_writer_dml.go, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1354
- Unit test
- No code
```release-note
```
=> dispatcher: fix bug in prepareDMLs

pkg/common/event/dml_event.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_service_test.go
Issue Number: close #1389 
- Unit test
- No code
```release-note
```
=> eventBroker: fix out-of-order issue with DML events and syncpoint events

maintainer/operator/operator_merge_split.go
- Unit test
- No code
```release-note
```
=> log: add some log for debug merge-split operator

downstreamadapter/eventcollector/event_collector.go, logservice/eventstore/event_store.go, logservice/logpuller/region_event_handler.go
Issue Number: ref #1328
Use atomic value to store coordinator info.
- Unit test
- No code
```release-note
```
=> *: use atomic value to store coordinator info

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/event_collector.go, logservice/eventstore/event_store.go, logservice/eventstore/event_store_test.go, metrics/grafana/ticdc_new_arch.json, pkg/eventservice/dispatcher_stat.go, pkg/eventservice/event_broker.go, pkg/eventservice/event_scanner.go, pkg/eventservice/event_service.go, pkg/eventservice/event_service_test.go, pkg/eventservice/metrics_collector.go, pkg/metrics/event_service.go
Issue Number: close #1428
* add event service channel size to detect whether the channel is full, most of the time, it should be empty.
* event service channel size is set to s reasonable number, 32.
* refactor some code, remove impossible error and redundant error check logic
* return as soon as possible to reduce the loop complexity.
- Unit test
```release-note
`None`
```
=> metrics: add more new metrics about the event service

tests/scripts/download-integration-test-binaries.sh
Issue Number: ref #1401 
- No code
```release-note
None
```
=> revert temporary changes

downstreamadapter/sink/mysql/causality/conflict_detector.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1425
- Unit test
- No code
```release-note
```
=> dispatcher: fix panic in conflict detector

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/helper.go, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: ref https://github.com/pingcap/ticdc/issues/1437
add some logs for the issue
it can't reproduce now, so we just add some logs for future.
- Unit test
- No code
```release-note
```
=> Add log for dispatcher handle events

coordinator/changefeed/changefeed.go
Issue Number: close #1450
- Unit test
```release-note
`None`.
```
=> coordinator: fix a data race in changefeed

maintainer/maintainer_controller_helper.go, maintainer/operator/operator_controller.go
- Unit test
- No code
```release-note
```
=> Make merge operator tool more robust

cmd/kafka-consumer/writer.go, downstreamadapter/dispatchermanager/helper.go, downstreamadapter/sink/kafka/sink.go, downstreamadapter/sink/mysql/causality/helper.go, pkg/common/table_info_helper.go, pkg/compression/compress.go, pkg/errors/error.go, pkg/sink/mysql/mysql_writer_ddl.go
Issue Number: close #1463 
- Unit test
- No code
```release-note
`None`.
```
=> *: adjust some code fix some tiny problem

logservice/logpuller/subscription_client.go, logservice/logpuller/subscription_client_test.go, maintainer/maintainer.go, maintainer/maintainer_controller.go, maintainer/maintainer_controller_test.go, maintainer/maintainer_manager.go, maintainer/maintainer_manager_test.go, maintainer/maintainer_test.go, maintainer/split/region_count_splitter.go, maintainer/split/region_count_splitter_test.go, maintainer/split/splitter.go, pkg/common/context/app_context.go, server/server.go, server/server_prepare.go
Issue Number: ref https://github.com/pingcap/ticdc/issues/1451
- Unit test
- No code
```release-note
```
=> Set regionCache as a global shared component in appcontext

logservice/schemastore/persist_storage.go, logservice/schemastore/persist_storage_ddl_handlers.go, pkg/binlog-filter/filter.go, pkg/eventservice/event_scanner.go, pkg/filter/ddl.go
Issue Number: close #1476
- Unit test
- No code
```release-note
```
=> schemastore: support add fulltext index

downstreamadapter/eventcollector/dispatcher_stat.go, pkg/common/event/sync_point_event.go, pkg/eventservice/event_broker.go
Issue Number: close #1479 
- Unit test
- No code
```release-note
```
=> event: add seq to syncpoint event

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/dispatcher_stat_test.go, downstreamadapter/eventcollector/helper.go
Issue Number: close #1499
Previously we process BatchDMLEvents one by one for simplicity. This pr support process a batch of BatchDMLEvents every time.
- Unit test
- No code
```release-note
```
=> eventcollector: support batch process for BatchDMLEvents

pkg/eventservice/event_broker.go
- Unit test
- No code
```release-note
```
=> eventbroker: fix syncpoint seq

pkg/eventservice/dispatcher_stat.go, pkg/eventservice/dispatcher_stat_test.go, pkg/eventservice/event_broker_test.go
Issue Number: close #1524 
- Unit test
- No code
```release-note
```
=> eventbroker: filter out invalid resolved ts

downstreamadapter/sink/kafka/helper.go
- Unit test
- No code
```release-note
```
=> sink: add error check in kafka sink initialization

logservice/eventstore/event_store.go, metrics/grafana/ticdc_new_arch.json, pkg/metrics/event_store.go
Issue Number: close #1528
- Unit test
- No code
```release-note
```
=> eventstore: fix input write bytes metrics

tests/integration_tests/fail_over_ddl_mix_with_syncpoint/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1477
- Unit test
- No code
```release-note
```
=> test: recover `fail_over_ddl_mix_with_syncpoint` intergration test

downstreamadapter/eventcollector/dispatcher_stat.go
Issue Number: close #1542
Avoid remove & add path in dynamic stream when reset dispatcher.
Originally, when a dispatcher reset and pause at the same time, it will be removed and added from dynamic stream, and its path in ds is in normal state so it will never send resume request to event broker.
- Unit test
- No code
```release-note
```
=> eventcollector: avoid remove & add path when reset dispatcher

cmd/kafka-consumer/writer.go, pkg/sink/codec/simple/decoder.go, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: ref #442
Fix and add kafka_simple_basic test case
- Unit test
```release-note
`None`.
```
=> codec: fix panic in kafka_simple_basic integration test

logservice/eventstore/event_store.go, tests/integration_tests/run_light_it_in_ci.sh
- Unit test
- No code
```release-note
```
=> eventstore: reduce ttl of idle subscriptions

downstreamadapter/eventcollector/helper.go
Issue Number: close #1571
- No code
```release-note
None
```
=> eventCollector: adjust verbos log

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/event_collector.go, pkg/messaging/message_center.go, pkg/node/node.go
Issue Number: close #1576 
- Unit test
- No code
```release-note
```
=> eventcollector: ignore the heartbeat for dispatchers which are not receving data

coordinator/controller.go, downstreamadapter/dispatchermanager/event_dispatcher_manager.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1575
* **Changefeed Creation Robustness**: Improved the `CreateChangefeed` logic to handle cases where a changefeed is being recreated immediately after removal. Instead of failing instantly if the changefeed is still in a 'scheduling' state, the system now retries up to 10 times with a 5-second delay between attempts, providing a grace period for the previous removal operation to complete.
* **Faster Changefeed Removal**: Optimized the `closeAllDispatchers` process by removing a blocking loop that explicitly waited for individual dispatchers to fully close. Dispatchers are now removed directly, leading to a quicker release of resources and accelerating the overall changefeed removal process.
- Unit test
- …
=> Remove changefeed more quickly

cmd/kafka-consumer/writer.go, cmd/pulsar-consumer/writer.go
Issue Number: close #1599
Adjust log level.
- Unit test
- No code
```release-note
```
=> consumer: avoid panic when execute ddl failed

logservice/eventstore/event_store.go, metrics/grafana/ticdc_new_arch.json
Issue Number: close #1628 
Separate memory quota metrics for event collector and log puller for more clear metrics.
- Unit test
- No code
```release-note
```
=> *: improve memory quota metrics

cmd/kafka-consumer/writer.go, cmd/pulsar-consumer/writer.go, downstreamadapter/dispatcher/basic_dispatcher.go, pkg/common/event/dml_event.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go, tests/integration_tests/run_heavy_it_in_ci.sh
- Unit test
- No code
```release-note
```
=> *: fix unstable tests

Makefile
Issue Number: close #1687
This PR introduces a new Makefile target, `integration_test_build_fast`, to accelerate the build process for integration tests.
**Problem:**
The existing `integration_test_build` target builds multiple components, some of which are not always required for running integration tests. This leads to longer wait times for developers, hindering productivity.
**Solution:**
The new `integration_test_build_fast` target is a streamlined version of the original. It focuses only on building the essential `cdc.test` and `cdc` binaries, omitting other components that are not always needed. This significantly reduces the build time.
Developers can now use `make integration_test_build_fast` to get a quicker build, making the local development and testing cycle more efficient. …
=> feat(Makefile): add `integration_test_build_fast` for faster developer iteration

downstreamadapter/eventcollector/dispatcher_stat.go, downstreamadapter/eventcollector/dispatcher_stat_test.go
Issue Number: close #1783 
- Unit test
```release-note
None
```
=> eventcollector: ignore same syncpoint

pkg/common/event/sync_point_event.go, pkg/common/event/sync_point_event_test.go, pkg/eventservice/event_broker.go
Issue Number: close #1814 
- Unit test
- No code
```release-note
```
=> event: fix syncpoint event encoding

downstreamadapter/sink/mysql/causality/conflict_detector.go, downstreamadapter/sink/mysql/sink.go, downstreamadapter/sink/mysql/sink_test.go, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1713
- Unit test
- No code
```release-note
```
=> conflictDectector: Fix data race

downstreamadapter/sink/cloudstorage/dml_writers_test.go, tests/integration_tests/fail_over/run.sh
Issue Number: close #1827 
- Unit test
- No code
```release-note
```
=> test: fix unstable test

downstreamadapter/sink/mysql/sink_test.go, pkg/sink/mysql/mysql_writer_for_ddl_ts.go, pkg/sink/mysql/mysql_writer_test.go, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1831
- Unit test
- No code
```release-note
```
=> ddl: Increase created_at precision of ddl_ts

maintainer/barrier_event.go, maintainer/maintainer_controller_helper.go, maintainer/operator/operator_move.go, tests/integration_tests/ddl_with_random_move_table/run.sh, tests/integration_tests/run_heavy_it_in_ci.sh
Issue Number: close https://github.com/pingcap/ticdc/issues/1829
- Unit test
- No code
```release-note
```
=> scheduler: Not start any move if the target and the current node are on the same node

go.mod, go.sum, pkg/sink/codec/avro/arvo.go, pkg/sink/codec/avro/avro_test.go, pkg/sink/codec/avro/confluent_schema_registry.go, pkg/sink/codec/avro/confluent_schema_registry_test.go, pkg/sink/codec/avro/glue_schema_registry.go, pkg/sink/codec/simple/marshaller.go
This is an cherry-pick of https://github.com/pingcap/tiflow/pull/12191
Issue Number: ref https://github.com/pingcap/tiflow/issues/11994
- Unit test
- No code
```release-note
`None`.
```
=> codec: fix incorrect encoding default "null" in Avro protocol

tests/integration_tests/ddl_wait/run.sh
Issue Number: close #1856 
- Unit test
- No code
```release-note
```
=> test: fix unstable test `ddl_wait`

coordinator/changefeed/backoff.go, coordinator/changefeed/backoff_test.go, coordinator/changefeed/changefeed_db.go, coordinator/changefeed/changefeed_db_test.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1897
1. avoid data race in backoff
2. refactor StopByChangefeedID() for duplicate code
- Unit test
- No code
```release-note
```
=> coordinator: fix test assert and refactor `StopByChangefeedID`

pkg/scheduler/replica/replication.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1923
- Unit test
- No code
```release-note
```
=> maintainer: Fix data race

logservice/logpuller/region_event_handler.go
Issue Number: close #1397
- Unit test
- No code
```release-note
```
=> logpuller: remove unnecessary log

maintainer/maintainer_controller_test.go, maintainer/replica/split_span_checker.go, maintainer/replica/split_span_checker_test.go
- Unit test
- No code
```release-note
```
=> maintainer: fix unstable unit test

pkg/common/event/util.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1902
- Unit test
- No code
```release-note
```
=> ddl: translate TiDB feature to special comment when spliting queries

LICENSE, third-party-license.txt
Issue Number: close #1515 
- Unit test
- No code
```release-note
```
=> *: add license

downstreamadapter/sink/cloudstorage/dml_writers.go, downstreamadapter/sink/cloudstorage/encoding_group.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2031
- Unit test
- No code
```release-note
```
=> sink: fix data race in cloudstorage sink

logservice/logpuller/region_req_cache.go, logservice/logpuller/region_req_cache_test.go
Issue Number: close #2164 
```release-note
None
```
=> logpuller: fix a data race

maintainer/barrier_event.go, metrics/grafana/ticdc_new_arch.json
- Unit test
- No code
```release-note
```
=> metrics: update grafana for ddl 

pkg/common/event/mounter.go
Issue Number: ref #2288 
- No code
```
None
```
=> *: remove debug log

logservice/logpuller/subscription_client.go, logservice/schemastore/persist_storage.go, logservice/schemastore/schema_store.go, logservice/schemastore/unsorted_cache.go, logservice/schemastore/utils.go, logservice/txnutil/lock_resolver.go, pkg/eventservice/event_broker.go, pkg/txnutil/gc/gc_manager.go
Issue Number: close #2293
- Unit test
```release-note
`None`
```
=> logs: simplify logs and remove some useless log fields

downstreamadapter/dispatchermanager/dispatcher_manager.go, downstreamadapter/eventcollector/event_collector.go
Issue Number: close https://github.com/pingcap/ticdc/issues/1061
- Unit test
- No code
```release-note
```
=> metrics: removes the metric correctly about redo

logservice/eventstore/event_store_test.go
Issue Number: close #2366
* **Data Race Fix**: Introduced a `sync.Mutex` to the `mockSubscriptionClient` to prevent data races when concurrently accessing the `subscriptions` map.
* **Concurrency Safety**: The `Subscribe` and `Unsubscribe` methods now use the mutex to ensure thread-safe modifications to the internal subscription state.
* **Test Reliability**: Updated test assertions in `TestEventStoreInteractionWithSubClient` to properly acquire the mutex before inspecting the `subscriptions` map, ensuring accurate and reliable test results.
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html …
```
=> eventstore: fix data race

maintainer/replica/default_span_split_checker.go, maintainer/replica/default_span_split_checker_test.go, maintainer/replica/split_span_checker.go, maintainer/replica/split_span_checker_test.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2311
- Unit test
- No code
```release-note
```
=> scheduler: reduce query region count frequency 

maintainer/operator/helper.go, maintainer/operator/operator_controller.go
- Unit test
- No code
```release-note
```
=> operator: reduce print frequency of meanless log

tests/integration_tests/ddl_wait/run.sh, tests/integration_tests/ddl_wait/test.go, tests/integration_tests/run_heavy_it_in_ci.sh, tests/integration_tests/run_light_it_in_ci.sh
Issue Number: close #2327  
Move case `ddl_wait` to mysql heavy group.
```release-note
None
```
=> tests: fix unstable integration test `ddl_wait`

downstreamadapter/dispatchermanager/dispatcher_manager.go, maintainer/operator/operator_controller.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2384
- Unit test
- No code
```release-note
```
=> operatorController: fix panic

pkg/common/table_info.go, pkg/common/table_info_helper.go, pkg/filter/expr_filter.go, tests/integration_tests/event_filter/conf/cf.toml, tests/integration_tests/event_filter/conf/diff_config.toml, tests/integration_tests/event_filter/data/test.sql, tests/integration_tests/event_filter/run.sh
Issue Number: close #1500
It is a cherry pick of https://github.com/pingcap/tiflow/pull/12229 and https://github.com/pingcap/tiflow/pull/12211
* **Enhanced Event Filtering for Virtual Columns**: The core change enables the event filter to correctly process and apply filtering rules that involve virtual columns, addressing a previous limitation.
* **Optimized Virtual Column Handling**: The internal representation of virtual columns in `TableInfo` and `columnSchema` has been refactored from a simple count to storing specific offsets, allowing for more precise management.
* **Dynamic Evaluation with Caching**: A new mechanism dynamically computes virtual column values during filtering. This process is optimized by caching virtual column metadata (columns, offsets, field types) per table, …
=> eventfilter: support event filter with virtual column

maintainer/operator/operator_add_test.go, maintainer/operator/operator_merge_test.go, maintainer/operator/operator_occupy_test.go, maintainer/operator/operator_remove.go, maintainer/operator/operator_remove_test.go, maintainer/operator/operator_split_test.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2444
Added comprehensive unit tests for `OnNodeRemove` scenarios across all operator types in `maintainer/operator` package.
- **operator_add_test.go**: Tests for AddDispatcherOperator
- `TestAddOperator_DestNodeRemoved`: Verifies span is marked absent when destination node is removed during add operation
- **operator_remove_test.go**: Tests for RemoveDispatcherOperator
- `TestRemoveOperator_NodeRemovedBeforeStopped`: Node removed before reporting stopped status - operator finishes immediately
- **operator_split_test.go**: Tests for SplitDispatcherOperator
- `TestSplitOperator_OriginNodeRemovedBeforeStopped`: Origin node removed before stopped - span marked absent without executing split
- …
=> tests: add OnNodeRemove unit tests for all operator types

downstreamadapter/dispatchermanager/dispatcher_manager.go, downstreamadapter/dispatchermanager/dispatcher_manager_helper.go, downstreamadapter/dispatchermanager/task.go
Issue Number: close https://github.com/pingcap/ticdc/issues/2473
* **Asynchronous Dispatcher Removal**: The dispatcher removal process has been refactored from a synchronous, blocking operation to an asynchronous one, utilizing a dedicated thread pool to prevent blocking the main execution flow.
* **Dedicated Thread Pool**: A new `threadpool.ThreadPool` instance is introduced specifically for handling `RemoveDispatcherTask` operations, ensuring that dispatcher cleanup is managed efficiently in the background.
* **Retriable Removal Tasks**: A new `RemoveDispatcherTask` is defined, which attempts to close and remove a dispatcher. If the dispatcher cannot be closed immediately, the task will automatically retry after a short delay, ensuring eventual cleanup.
* **Task Cancellation**: Logic …
=> dispatcherManager: Use threadpool to asynchronously handle remove dispatcher
